using Assets.Scripts.databases.game;
using Assets.Scripts.databases.game.shops;
using Assets.Scripts.item;
using Assets.Scripts.logger;
using Assets.Scripts.node;
using Assets.Scripts.skills;
using Assets.Scripts.stats;
using Assets.Scripts.util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace Assets.Scripts.databases
{
    /// <summary>
    /// Items stored in this game
    /// </summary>
    public class ItemDatabase : CRDatabase
    {
        /// <summary>
        /// The inventory icons
        /// </summary>
        private Sprite[] InventoryIcon;
        
        /// <summary>
        /// Builds the item database
        /// </summary>
        public override void BuildDatabase()
        {
            CrLogger.Log(this, "Building item database...");

            items = new List<DbElement>()
            {
                new Item(0, "Hedgehog plushie", false, new Stats(0,0,0,20,0,0,0,0,0,0), new SkillRequirement(), "A nice plushie, it says POG on the label.", false, true, EquipmentType.MAINHAND, 100),
                new Item(1, "Rat plushie", false, new Stats(), new SkillRequirement(), "When you squeeze it, it squeeks!", false, true, EquipmentType.MAINHAND, 100),
                new Item(2, "Cat plushie", false, new Stats(), new SkillRequirement(), "Meeeeeeeow", false, true, EquipmentType.MAINHAND, 100),
                new Item(3, "Dog plushie", false, new Stats(), new SkillRequirement(), "He doesn't do much but he's a good boy.", false, true, EquipmentType.MAINHAND, 100),
                new Item(4, "Wood sword", false, new Stats(), new SkillRequirement(), "A regular sword made out of wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(5, "Bronze sword", false, new Stats(), new SkillRequirement(), "A regular sword made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(6, "Silver sword", false, new Stats(), new SkillRequirement(), "A regular sword made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(7, "Gold sword", false, new Stats(), new SkillRequirement(), "A regular sword made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(8, "Platinum sword", false, new Stats(), new SkillRequirement(), "A regular sword made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(9, "Ruby sword", false, new Stats(), new SkillRequirement(), "A sword made out of platinum. There's a ruby in the rain-guard.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(10, "Emerald sword", false, new Stats(), new SkillRequirement(), "A sword made out of platinum. There's an emerald in the rain-guard.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(11, "Sapphire sword", false, new Stats(), new SkillRequirement(), "A sword made out of platinum. There's a sapphire in the rain-guard.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(12, "Wood shield", false, new Stats(), new SkillRequirement(), "A regular shield made out of wood.", false, true, EquipmentType.OFFHAND, 10),
                new Item(13, "Bronze shield", false, new Stats(), new SkillRequirement(), "A regular shield made out of bronze.", false, true, EquipmentType.OFFHAND, 50),
                new Item(14, "Silver shield", false, new Stats(), new SkillRequirement(), "A regular shield made out of silver.", false, true, EquipmentType.OFFHAND, 100),
                new Item(15, "Gold shield", false, new Stats(), new SkillRequirement(), "A regular shield made out of gold.", false, true, EquipmentType.OFFHAND, 200),
                new Item(16, "Platinum shield", false, new Stats(), new SkillRequirement(), "A regular shield made out of platinum.", false, true, EquipmentType.OFFHAND, 500),
                new Item(17, "Ruby shield", false, new Stats(), new SkillRequirement(), "A shield made out of platinum. There's a ruby at the center of the disc.", false, true, EquipmentType.OFFHAND, 1500),
                new Item(18, "Emerald shield", false, new Stats(), new SkillRequirement(), "A shield made out of platinum. There's an emerald at the center of the disc.", false, true, EquipmentType.OFFHAND, 1500),
                new Item(19, "Sapphire shield", false, new Stats(), new SkillRequirement(), "A shield made out of platinum. There's a sapphire at the center of the disc.", false, true, EquipmentType.OFFHAND, 1500),
                new Item(20, "Wood dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(21, "Bronze dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(22, "Silver dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(23, "Gold dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(24, "Platinum dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(25, "Ruby dagger", false, new Stats(), new SkillRequirement(), "A dagger made out of platinum. There's a ruby in the rain-guard.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(26, "Emerald dagger", false, new Stats(), new SkillRequirement(), "A dagger made out of platinum. There's an emerald in the rain-guard.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(27, "Sapphire dagger", false, new Stats(), new SkillRequirement(), "A dagger made out of platinum. There's a sapphire in the rain-guard.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(28, "Wood greataxe", false, new Stats(), new SkillRequirement(), "A regular greataxe made out of wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(29, "Bronze greataxe", false, new Stats(), new SkillRequirement(), "A regular greataxe made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(30, "Silver greataxe", false, new Stats(), new SkillRequirement(), "A regular greataxe made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(31, "Gold greataxe", false, new Stats(), new SkillRequirement(), "A regular greataxe made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(32, "Platinum greataxe", false, new Stats(), new SkillRequirement(), "A regular greataxe made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(33, "Ruby greataxe", false, new Stats(), new SkillRequirement(), "A greataxe made out of platinum. There's a ruby inbetween the blades.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(34, "Emerald greataxe", false, new Stats(), new SkillRequirement(), "A greataxe made out of platinum. There's an emerald inbetween the blades.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(35, "Sapphire greataxe", false, new Stats(), new SkillRequirement(), "A greataxe made out of platinum. There's a sapphire inbetween the blades.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(36, "Wood scythe", false, new Stats(), new SkillRequirement(), "A regular scythe made out of wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(37, "Bronze scythe", false, new Stats(), new SkillRequirement(), "A regular scythe made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(38, "Silver scythe", false, new Stats(), new SkillRequirement(), "A regular scythe made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(39, "Gold scythe", false, new Stats(), new SkillRequirement(), "A regular scythe made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(40, "Platinum scythe", false, new Stats(), new SkillRequirement(), "A regular scythe made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(41, "Ruby scythe", false, new Stats(), new SkillRequirement(), "A scythe made out of platinum. The attachment ring is decorated with a ruby.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(42, "Emerald scythe", false, new Stats(), new SkillRequirement(), "A scythe made out of platinum. The attachment ring is decorated with an emerald.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(43, "Sapphire scythe", false, new Stats(), new SkillRequirement(), "A scythe made out of platinum. The attachment ring is decorated with a sapphire.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(44, "Bronze helmet", false, new Stats(), new SkillRequirement(), "A regular helmet made out of bronze.", false, true, EquipmentType.HEAD, 50),
                new Item(45, "Silver helmet", false, new Stats(), new SkillRequirement(), "A regular helmet made out of silver.", false, true, EquipmentType.HEAD, 100),
                new Item(46, "Gold helmet", false, new Stats(), new SkillRequirement(), "A regular helmet made out of gold.", false, true, EquipmentType.HEAD, 200),
                new Item(47, "Platinum helmet", false, new Stats(), new SkillRequirement(), "A regular helmet made out of platinum.", false, true, EquipmentType.HEAD, 500),
                new Item(48, "Ruby helmet", false, new Stats(), new SkillRequirement(), "A helmet made out of platinum. It is decorated with a ruby.", false, true, EquipmentType.HEAD, 1500),
                new Item(49, "Emerald helmet", false, new Stats(), new SkillRequirement(), "A helmet made out of platinum. It is decorated with an emerald.", false, true, EquipmentType.HEAD, 1500),
                new Item(50, "Sapphire helmet", false, new Stats(), new SkillRequirement(), "A helmet made out of platinum. It is decorated with a sapphire.", false, true, EquipmentType.HEAD, 1500),
                new Item(51, "Bronze chestplate", false, new Stats(), new SkillRequirement(), "A regular chestplate made out of bronze.", false, true, EquipmentType.TORSO, 50),
                new Item(52, "Silver chestplate", false, new Stats(), new SkillRequirement(), "A regular chestplate made out of silver.", false, true, EquipmentType.TORSO, 100),
                new Item(53, "Gold chestplate", false, new Stats(), new SkillRequirement(), "A regular chestplate made out of gold.", false, true, EquipmentType.TORSO, 200),
                new Item(54, "Platinum chestplate", false, new Stats(), new SkillRequirement(), "A regular chestplate made out of platinum.", false, true, EquipmentType.TORSO, 500),
                new Item(55, "Ruby chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made out of platinum. It is decorated with a ruby.", false, true, EquipmentType.TORSO, 1500),
                new Item(56, "Emerald chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made out of platinum. It is decorated with an emerald.", false, true, EquipmentType.TORSO, 1500),
                new Item(57, "Sapphire chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made out of platinum. It is decorated with a sapphire.", false, true, EquipmentType.TORSO, 1500),
                new Item(58, "Bronze legs", false, new Stats(), new SkillRequirement(), "A regular pair of legs, made out of bronze.", false, true, EquipmentType.LEGS, 50),
                new Item(59, "Silver legs", false, new Stats(), new SkillRequirement(), "A regular pair of legs, made out of silver.", false, true, EquipmentType.LEGS, 100),
                new Item(60, "Gold legs", false, new Stats(), new SkillRequirement(), "A regular pair of legs, made out of gold.", false, true, EquipmentType.LEGS, 200),
                new Item(61, "Platinum legs", false, new Stats(), new SkillRequirement(), "A regular pair of legs, made out of platinum.", false, true, EquipmentType.LEGS, 500),
                new Item(62, "Ruby legs", false, new Stats(), new SkillRequirement(), "A pair of legs made out of platinum. They're decorated with a ruby.", false, true, EquipmentType.LEGS, 1500),
                new Item(63, "Emerald legs", false, new Stats(), new SkillRequirement(), "A pair of legs made out of platinum. They're decorated with an emerald.", false, true, EquipmentType.LEGS, 1500),
                new Item(64, "Sapphire legs", false, new Stats(), new SkillRequirement(), "A pair of legs made out of platinum. They're decorated with a sapphire.", false, true, EquipmentType.LEGS, 1500),
                new Item(65, "Bronze boots", false, new Stats(), new SkillRequirement(), "A regular pair of boots made out of bronze.", false, true, EquipmentType.FEET, 50),
                new Item(66, "Silver boots", false, new Stats(), new SkillRequirement(), "A regular pair of boots made out of silver.", false, true, EquipmentType.FEET, 100),
                new Item(67, "Gold boots", false, new Stats(), new SkillRequirement(), "A regular pair of boots made out of gold.", false, true, EquipmentType.FEET, 200),
                new Item(68, "Platinum boots", false, new Stats(), new SkillRequirement(), "A regular pair of boots made out of platinum.", false, true, EquipmentType.FEET, 500),
                new Item(69, "Ruby boots", false, new Stats(), new SkillRequirement(), "A pair of boots made out of platinum. The nose is decorated with a ruby.", false, true, EquipmentType.FEET, 1500),
                new Item(70, "Emerald boots", false, new Stats(), new SkillRequirement(), "A boots made out of platinum. The nose is decorated with an emerald.", false, true, EquipmentType.FEET, 1500),
                new Item(71, "Sapphire boots", false, new Stats(), new SkillRequirement(), "A boots made out of platinum. The nose is decorated with a sapphire.", false, true, EquipmentType.FEET, 1500),
                new Item(72, "Ruby amulet", false, new Stats(), new SkillRequirement(), "An amulet made of gold, with a beatiful ruby on it.", false, true, EquipmentType.AMULET, 1500),
                new Item(73, "Emerald amulet", false, new Stats(), new SkillRequirement(), "An amulet made of gold, with a beatiful emerald on it.", false, true, EquipmentType.AMULET, 1500),
                new Item(74, "Sapphire amulet", false, new Stats(), new SkillRequirement(), "A an amulet made of gold, with a beatiful sapphire on it.", false, true, EquipmentType.AMULET, 1500),
                new Item(75, "Rock", true, new Stats(), new SkillRequirement(), "A light rock that can easily gain attention from someone by being thrown at them.", false, true, EquipmentType.AMMO, 0),
                new Item(76, "Wood bow", false, new Stats(), new SkillRequirement(), "A regular bow made out of Wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(77, "Bronze bow", false, new Stats(), new SkillRequirement(), "A regular bow made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(78, "Silver bow", false, new Stats(), new SkillRequirement(), "A regular bow made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(79, "Gold bow", false, new Stats(), new SkillRequirement((int)SKILLS.ARCHER, 30), "A regular bow made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(80, "Platinum bow", false, new Stats(), new SkillRequirement(), "A regular bow made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(81, "Ruby bow", false, new Stats(), new SkillRequirement(), "A bow made out of platinum. It's decorated with a ruby close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(82, "Emerald bow", false, new Stats(), new SkillRequirement(), "A bow made out of platinum. It's decorated with an emerald close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(83, "Sapphire bow", false, new Stats(), new SkillRequirement(), "A bow made out of platinum. It's decorated with a sapphire close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(84, "Wood crossbow", false, new Stats(), new SkillRequirement(), "A regular crossbow made out of Wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(85, "Bronze crossbow", false, new Stats(), new SkillRequirement(), "A regular crossbow made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(86, "Silver crossbow", false, new Stats(), new SkillRequirement(), "A regular crossbow made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(87, "Gold crossbow", false, new Stats(), new SkillRequirement(), "A regular crossbow made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(88, "Platinum crossbow", false, new Stats(), new SkillRequirement(), "A regular crossbow made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(89, "Ruby crossbow", false, new Stats(), new SkillRequirement(), "A crossbow made out of platinum. It's stock is decorated with a ruby.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(90, "Emerald crossbow", false, new Stats(), new SkillRequirement(), "A crossbow made out of platinum. It's stock is decorated with an emerald.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(91, "Sapphire crossbow", false, new Stats(), new SkillRequirement(), "A crossbow made out of platinum. It's stock is decorated with a sapphire.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(92, "Wood shortbow", false, new Stats(), new SkillRequirement(), "A regular shortbow made out of Wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(93, "Bronze shortbow", false, new Stats(), new SkillRequirement(), "A regular shortbow made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(94, "Silver shortbow", false, new Stats(), new SkillRequirement(), "A regular shortbow made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(95, "Gold shortbow", false, new Stats(), new SkillRequirement(), "A regular shortbow made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(96, "Platinum shortbow", false, new Stats(), new SkillRequirement(), "A regular shortbow made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(97, "Ruby shortbow", false, new Stats(), new SkillRequirement(), "A shortbow made out of platinum. It's decorated with a ruby close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(98, "Emerald shortbow", false, new Stats(), new SkillRequirement(), "A shortbow made out of platinum. It's decorated with an emerald close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(99, "Sapphire shortbow", false, new Stats(), new SkillRequirement(), "A shortbow made out of platinum. It's decorated with a sapphire close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(100, "Wood longbow", false, new Stats(), new SkillRequirement(), "A regular longbow made out of Wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(101, "Bronze longbow", false, new Stats(), new SkillRequirement(), "A regular longbow made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(102, "Silver longbow", false, new Stats(), new SkillRequirement(), "A regular longbow made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(103, "Gold longbow", false, new Stats(), new SkillRequirement(), "A regular longbow made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(104, "Platinum longbow", false, new Stats(), new SkillRequirement(), "A regular longbow made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(105, "Ruby longbow", false, new Stats(), new SkillRequirement(), "A longbow made out of platinum. It's decorated with a ruby close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(106, "Emerald longbow", false, new Stats(), new SkillRequirement(), "A longbow made out of platinum. It's decorated with an emerald close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(107, "Sapphire longbow", false, new Stats(), new SkillRequirement(), "A longbow made out of platinum. It's decorated with a sapphire close to the arrow rest.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(108, "Wood chakram", true, new Stats(), new SkillRequirement(), "A regular chakram made out of Wood.", false, true, EquipmentType.MAINHAND, 10),
                new Item(109, "Bronze chakram", true, new Stats(), new SkillRequirement(), "A regular chakram made out of bronze.", false, true, EquipmentType.MAINHAND, 50),
                new Item(110, "Silver chakram", true, new Stats(), new SkillRequirement(), "A regular chakram made out of silver.", false, true, EquipmentType.MAINHAND, 100),
                new Item(111, "Gold chakram", true, new Stats(), new SkillRequirement(), "A regular chakram made out of gold.", false, true, EquipmentType.MAINHAND, 200),
                new Item(112, "Platinum chakram", true, new Stats(), new SkillRequirement(), "A regular chakram made out of platinum.", false, true, EquipmentType.MAINHAND, 500),
                new Item(113, "Ruby chakram", true, new Stats(), new SkillRequirement(), "A chakram made out of platinum. It's handle is decorated with a ruby.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(114, "Emerald chakram", true, new Stats(), new SkillRequirement(), "A chakram made out of platinum. It's handle is decorated with an emerald.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(115, "Sapphire chakram", true, new Stats(), new SkillRequirement(), "A chakram made out of platinum. It's handle is decorated with a sapphire.", false, true, EquipmentType.MAINHAND, 1500),
                new Item(116, "Wood arrow", true, new Stats(), new SkillRequirement(), "A regular arrow made out of Wood.", false, true, EquipmentType.AMMO, 1),
                new Item(117, "Bronze arrow", true, new Stats(), new SkillRequirement(), "A regular arrow, with a bronze tip.", false, true, EquipmentType.AMMO, 5),
                new Item(118, "Silver arrow", true, new Stats(), new SkillRequirement(), "A regular arrow, with a silver tip.", false, true, EquipmentType.AMMO, 10),
                new Item(119, "Gold arrow", true, new Stats(), new SkillRequirement(), "A regular arrow, with a gold tip.", false, true, EquipmentType.AMMO, 20),
                new Item(120, "Platinum arrow", true, new Stats(), new SkillRequirement(), "A regular arrow, with a platinum tip.", false, true, EquipmentType.AMMO, 50),
                new Item(121, "Ruby arrow", true, new Stats(), new SkillRequirement(), "An arrow made out of platinum. Its tip is made out of ruby.", false, true, EquipmentType.AMMO, 150),
                new Item(122, "Emerald arrow", true, new Stats(), new SkillRequirement(), "An arrow made out of platinum. Its tip is made out of emerald.", false, true, EquipmentType.AMMO, 150),
                new Item(123, "Sapphire arrow", true, new Stats(), new SkillRequirement(), "An arrow made out of platinum. Its tip is made out of sapphire.", false, true, EquipmentType.AMMO, 150),
                new Item(124, "Berry seeds", true, new Stats(), new SkillRequirement(), "Plant these in the ground and a berry bush might grow!", false, false, EquipmentType.NONE, 15),
                new Item(125, "Wood bolt", true, new Stats(), new SkillRequirement(), "A regular bolt made out of Wood.", false, true, EquipmentType.AMMO, 1),
                new Item(126, "Bronze bolt", true, new Stats(), new SkillRequirement(), "A regular bolt made out of bronze.", false, true, EquipmentType.AMMO, 5),
                new Item(127, "Silver bolt", true, new Stats(), new SkillRequirement(), "A regular bolt made out of silver.", false, true, EquipmentType.AMMO, 10),
                new Item(128, "Gold bolt", true, new Stats(), new SkillRequirement(), "A regular bolt made out of gold.", false, true, EquipmentType.AMMO, 20),
                new Item(129, "Platinum bolt", true, new Stats(), new SkillRequirement(), "A regular bolt made out of platinum.", false, true, EquipmentType.AMMO, 50),
                new Item(130, "Ruby bolt", true, new Stats(), new SkillRequirement(), "A bolt made out of platinum. Its tip is made out of ruby.", false, true, EquipmentType.AMMO, 150),
                new Item(131, "Emerald bolt", true, new Stats(), new SkillRequirement(), "A bolt made out of platinum. Its tip is made out of emerald.", false, true, EquipmentType.AMMO, 150),
                new Item(132, "Sapphire bolt", true, new Stats(), new SkillRequirement(), "A bolt made out of platinum. Its tip is made out of sapphire.", false, true, EquipmentType.AMMO, 150),
                new Item(133, "Green leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a green deer.", false, true, EquipmentType.HEAD, 50),
                new Item(134, "Turquoise leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a turquoise deer.", false, true, EquipmentType.HEAD, 100),
                new Item(135, "Blue leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a blue deer.", false, true, EquipmentType.HEAD, 200),
                new Item(136, "Purple leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a purple deer.", false, true, EquipmentType.HEAD, 500),
                new Item(137, "Red leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a red deer.", false, true, EquipmentType.HEAD, 500),
                new Item(138, "Black leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a black deer.", false, true, EquipmentType.HEAD, 1000),
                new Item(139, "White leather helmet", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a white deer.", false, true, EquipmentType.HEAD, 1000),
                new Item(140, "White leather helmet(r)", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a white deer. It's decorated with a big ruby.", false, true, EquipmentType.HEAD, 1500),
                new Item(141, "White leather helmet(e)", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a white deer. It's decorated with a big emerald.", false, true, EquipmentType.HEAD, 1500),
                new Item(142, "White leather helmet(s)", false, new Stats(), new SkillRequirement(), "A helmet made with the leather from a white deer. It's decorated with a big sapphire.", false, true, EquipmentType.HEAD, 1500),
                new Item(143, "Green leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a green deer.", false, true, EquipmentType.TORSO, 50),
                new Item(144, "Turquoise leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a turquoise deer.", false, true, EquipmentType.TORSO, 100),
                new Item(145, "Blue leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a blue deer.", false, true, EquipmentType.TORSO, 200),
                new Item(146, "Purple leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a purple deer.", false, true, EquipmentType.TORSO, 500),
                new Item(147, "Red leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a red deer.", false, true, EquipmentType.TORSO, 500),
                new Item(148, "Black leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a black deer.", false, true, EquipmentType.TORSO, 1000),
                new Item(149, "White leather chestplate", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a white deer.", false, true, EquipmentType.TORSO, 1000),
                new Item(150, "White leather chestplate(r)", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a white deer. It's decorated with a big ruby.", false, true, EquipmentType.TORSO, 1500),
                new Item(151, "White leather chestplate(e)", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a white deer. It's decorated with a big emerald.", false, true, EquipmentType.TORSO, 1500),
                new Item(152, "White leather chestplate(s)", false, new Stats(), new SkillRequirement(), "A chestplate made with the leather from a white deer. It's decorated with a big sapphire.", false, true, EquipmentType.TORSO, 1500),
                new Item(153, "Green leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a green deer.", false, true, EquipmentType.LEGS, 50),
                new Item(154, "Turquoise leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a turquoise deer.", false, true, EquipmentType.LEGS, 100),
                new Item(155, "Blue leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a blue deer.", false, true, EquipmentType.LEGS, 200),
                new Item(156, "Purple leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a purple deer.", false, true, EquipmentType.LEGS, 500),
                new Item(157, "Red leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a red deer.", false, true, EquipmentType.LEGS, 500),
                new Item(158, "Black leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a black deer.", false, true, EquipmentType.LEGS, 1000),
                new Item(159, "White leather legs", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a white deer.", false, true, EquipmentType.LEGS, 1000),
                new Item(160, "White leather legs(r)", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a white deer. It's decorated with a ruby.", false, true, EquipmentType.LEGS, 1500),
                new Item(161, "White leather legs(e)", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a white deer. It's decorated with an emerald.", false, true, EquipmentType.LEGS, 1500),
                new Item(162, "White leather legs(s)", false, new Stats(), new SkillRequirement(), "A pair of legs made with the leather from a white deer. It's decorated with a sapphire.", false, true, EquipmentType.LEGS, 1500),
                new Item(163, "Green leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a green deer.", false, true, EquipmentType.FEET, 50),
                new Item(164, "Turquoise leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a turquoise deer.", false, true, EquipmentType.FEET, 100),
                new Item(165, "Blue leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a blue deer.", false, true, EquipmentType.FEET, 200),
                new Item(166, "Purple leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a purple deer.", false, true, EquipmentType.FEET, 500),
                new Item(167, "Red leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a red deer.", false, true, EquipmentType.FEET, 500),
                new Item(168, "Black leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a black deer.", false, true, EquipmentType.FEET, 1000),
                new Item(169, "White leather boots", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a white deer.", false, true, EquipmentType.FEET, 1000),
                new Item(170, "White leather boots(r)", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a white deer. It's decorated with a ruby.", false, true, EquipmentType.FEET, 1500),
                new Item(171, "White leather boots(e)", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a white deer. It's decorated with an emerald.", false, true, EquipmentType.FEET, 1500),
                new Item(172, "White leather boots(s)", false, new Stats(), new SkillRequirement(), "A pair of boots made with the leather from a white deer. It's decorated with a sapphire.", false, true, EquipmentType.FEET, 1500),
                new Item(173, "Rodent trap", true, new Stats(), new SkillRequirement(), "Useful for catching rodents.", false, false, EquipmentType.NONE, 100),
                new Item(174, "Bird trap", true, new Stats(), new SkillRequirement(), "Conveniently made with two spoons.", false, false, EquipmentType.NONE, 100),
                new Item(175, "Deer bait", true, new Stats(), new SkillRequirement(), "The smell lures deer.", false, false, EquipmentType.NONE, 100),
                new Item(176, "Game call", false, new Stats(), new SkillRequirement(), "An odd sounding instrument that mimics the sound of deer.", false, false, EquipmentType.NONE, 100),
                new Item(177, "Green deer leather", true, new Stats(), new SkillRequirement(), "Leather that you took from a dead green deers body. you monster.", false, false, EquipmentType.NONE, 20),
                new Item(178, "Turquoise deer leather", true, new Stats(), new SkillRequirement(), "Leather that you took from a dead turquoise deers body. you monster.", false, false, EquipmentType.NONE, 50),
                new Item(179, "Blue deer leather", true, new Stats(), new SkillRequirement(), "Leather that you took from a dead blue deers body. you monster.", false, false, EquipmentType.NONE, 100),
                new Item(180, "Purple deer leather", true, new Stats(), new SkillRequirement(), "Leather that you took from a dead purple deers body. you monster.", false, false, EquipmentType.NONE, 200),
                new Item(181, "Red deer leather", true, new Stats(), new SkillRequirement(), "Leather that you took from a dead red deers body. you monster.", false, false, EquipmentType.NONE, 200),
                new Item(182, "Black deer leather", true, new Stats(), new SkillRequirement(), "Leather that you took from a dead black deers body. you monster.", false, false, EquipmentType.NONE, 400),
                new Item(183, "White deer leather", true, new Stats(), new SkillRequirement(), "Leather from a magnificent white deer. I hope you realize you might have killed the last of it's species.", false, false, EquipmentType.NONE, 400),
                new Item(184, "Green deer meat", true, new Stats(), new SkillRequirement(), "Yuck, only poor folks eat green deer meat.", false, false, EquipmentType.NONE, 10),
                new Item(185, "Turquoise deer meat", true, new Stats(), new SkillRequirement(), "The commoners favorite meat.", false, false, EquipmentType.NONE, 20),
                new Item(186, "Blue deer meat", true, new Stats(), new SkillRequirement(), "Tastes the same as pig, and they've spent their lives rolling around in the mud.", false, false, EquipmentType.NONE, 50),
                new Item(187, "Purple deer meat", true, new Stats(), new SkillRequirement(), "Deer meat with a wealthy taste.", false, true, EquipmentType.NONE, 50),
                new Item(188, "Red deer meat", true, new Stats(), new SkillRequirement(), "Doctors say eating red meat is bad for you.. but it tastes good so who cares.", false, false, EquipmentType.NONE, 100),
                new Item(189, "Black deer meat", true, new Stats(), new SkillRequirement(), "Finally some good fucking food.", false, false, EquipmentType.NONE, 200),
                new Item(190, "White deer meat", true, new Stats(), new SkillRequirement(), "Now this is some real gourmet shit.", false, false, EquipmentType.NONE, 200),
                new Item(191, "Raw green deer meat", true, new Stats(), new SkillRequirement(), "Yuck, only poor folks eat green deer meat.", false, false, EquipmentType.NONE, 5),
                new Item(192, "Raw Turquoise deer meat", true, new Stats(), new SkillRequirement(), "The commoners favorite meat.", false, false, EquipmentType.NONE, 10),
                new Item(193, "Raw blue deer meat", true, new Stats(), new SkillRequirement(), "Tastes the same as pig, and they've spent their lives rolling around in the mud.", false, false, EquipmentType.NONE, 25),
                new Item(194, "Raw purple deer meat", true, new Stats(), new SkillRequirement(), "Deer meat with a wealthy taste.", false, false, EquipmentType.NONE, 25),
                new Item(195, "Raw red deer meat", true, new Stats(), new SkillRequirement(), "Doctors say eating red meat is bad for you.. but it tastes good so who cares.", false, false, EquipmentType.NONE, 50),
                new Item(196, "Raw black deer meat", true, new Stats(), new SkillRequirement(), "Finally some good fucking food.", false, false, EquipmentType.NONE, 100),
                new Item(197, "Raw white deer meat", true, new Stats(), new SkillRequirement(), "Now this is some real gourmet shit.", false, false, EquipmentType.NONE, 100),
                new Item(198, "Mallard duck breast", true, new Stats(), new SkillRequirement(), "No more quacking for this duck.", false, false, EquipmentType.NONE, 20),
                new Item(199, "Tufted duck breast", true, new Stats(), new SkillRequirement(), "This duck waddled right into its own grave.", false, false, EquipmentType.NONE, 20),
                new Item(200, "Raw mallard duck breast", true, new Stats(), new SkillRequirement(), "No more quacking for this duck.", false, false, EquipmentType.NONE, 20),
                new Item(201, "Raw tufted duck breast", true, new Stats(), new SkillRequirement(), "This duck waddled right into its own grave.", false, false, EquipmentType.NONE, 20),
                new Item(202, "Canada goose breast", true, new Stats(), new SkillRequirement(), "I'm glad the big pest is dead.", false, false, EquipmentType.NONE, 50),
                new Item(203, "Greylag goose breast", true, new Stats(), new SkillRequirement(), "An average breast from an average goose.", false, false, EquipmentType.NONE, 20),
                new Item(204, "Pinkfoot goose breast", true, new Stats(), new SkillRequirement(), "Not sure if this was a goose or a duck.", false, false, EquipmentType.NONE, 20),
                new Item(205, "Raw canada goose breast", true, new Stats(), new SkillRequirement(), "I'm glad the big pest is dead.", false, false, EquipmentType.NONE, 50),
                new Item(206, "Raw greylag goose breast", true, new Stats(), new SkillRequirement(), "An average breast from an average goose.", false, false, EquipmentType.NONE, 20),
                new Item(207, "Raw pinkfoot goose breast", true, new Stats(), new SkillRequirement(), "Not sure if this was a goose or a duck.", false, false, EquipmentType.NONE, 20),
                new Item(208, "Feathers", true, new Stats(), new SkillRequirement(), "Plucked from the dead body of some bird.", false, false, EquipmentType.NONE, 2),
                new Item(209, "Rabbit", true, new Stats(), new SkillRequirement(), "Small, cute, and begging to be eaten.", false, false, EquipmentType.NONE, 15),
                new Item(210, "Hare", true, new Stats(), new SkillRequirement(), "Big, fast, and very nutritious.", false, false, EquipmentType.NONE, 15),
                new Item(211, "Raw rabbit", true, new Stats(), new SkillRequirement(), "Small, cute, and begging to be cooked.", false, false, EquipmentType.NONE, 10),
                new Item(212, "Raw hare", true, new Stats(), new SkillRequirement(), "Big, fast, and soon to be very nutritious.", false, false, EquipmentType.NONE, 10),
                new Item(213, "Lucky rabbit's foot", true, new Stats(), new SkillRequirement(), "The foot of a rabbit, it's said to bring luck when worn as an amulet.", false, false, EquipmentType.NONE, 100),
                new Item(214, "Lucky rabbit's amulet", true, new Stats(), new SkillRequirement(), "An amulet with the foot of a rabbit. Don't let the animal protection see this.", false, true, EquipmentType.AMULET, 100),
                new Item(215, "Pheasant breast", true, new Stats(), new SkillRequirement(), "It used to be a beatiful bird, and now it's a beatiful meal.", false, false, EquipmentType.NONE, 20),
                new Item(216, "Woodpigeon breast", true, new Stats(), new SkillRequirement(), "The vermin of the sky, good riddance.", false, false, EquipmentType.NONE, 20),
                new Item(217, "Corncrake breast", true, new Stats(), new SkillRequirement(), "A cute bird with a small brain.", false, false, EquipmentType.NONE, 20),
                new Item(218, "Raw pheasant breast", true, new Stats(), new SkillRequirement(), "It used to be a beatiful bird, and now it's a beatiful corpse.", false, false, EquipmentType.NONE, 20),
                new Item(219, "Raw woodpigeon breast", true, new Stats(), new SkillRequirement(), "The vermin of the sky, good riddance.", false, false, EquipmentType.NONE, 20),
                new Item(220, "Raw corncrake breast", true, new Stats(), new SkillRequirement(), "A cute bird with a small brain.", false, false, EquipmentType.NONE, 20),
                new Item(221, "Wood fishing rod", false, new Stats(), new SkillRequirement(), "A shabby wooden fishing rod.", false, false, EquipmentType.NONE, 10),
                new Item(222, "Bronze fishing rod", false, new Stats(), new SkillRequirement(), "A bronze fishing rod, used for fishing.", false, false, EquipmentType.NONE, 50),
                new Item(223, "Silver fishing rod", false, new Stats(), new SkillRequirement(), "A silver fishing rod, also used for fishing.", false, false, EquipmentType.NONE, 100),
                new Item(224, "Gold fishing rod", false, new Stats(), new SkillRequirement(), "A gold fishing rod. mainly used for fishing.", false, false, EquipmentType.NONE, 200),
                new Item(225, "Platinum fishing rod", false, new Stats(), new SkillRequirement(), "A platinum fishing rod. occasionally used for fishing.", false, false, EquipmentType.NONE, 500),
                new Item(226, "Ruby fishing rod", false, new Stats(), new SkillRequirement(), "A platinum fishing rod decorated with a ruby.", false, true, EquipmentType.NONE, 1500),
                new Item(227, "Emerald fishing rod", false, new Stats(), new SkillRequirement(), "A platinum fishing rod decorated with an emerald.", false, false, EquipmentType.NONE, 1500),
                new Item(228, "Sapphire fishing rod", false, new Stats(), new SkillRequirement(), "A platinum fishing rod decorated with a sapphire.", false, false, EquipmentType.NONE, 1500),
                new Item(229, "Wood harpoon", false, new Stats(), new SkillRequirement(), "A shabby wooden harpoon.", false, false, EquipmentType.NONE, 10),
                new Item(230, "Bronze harpoon", false, new Stats(), new SkillRequirement(), "A bronze harpoon.", false, false, EquipmentType.NONE, 50),
                new Item(231, "Silver harpoon", false, new Stats(), new SkillRequirement(), "A silver harpoon. cool.", false, false, EquipmentType.NONE, 100),
                new Item(232, "Gold harpoon", false, new Stats(), new SkillRequirement(), "A gold harpoon. epic.", false, false, EquipmentType.NONE, 200),
                new Item(233, "Platinum harpoon", false, new Stats(), new SkillRequirement(), "A platinum harpoon. wicked.", false, false, EquipmentType.NONE, 500),
                new Item(234, "Ruby harpoon", false, new Stats(), new SkillRequirement(), "A platinum harpoon decorated with a ruby.", false, false, EquipmentType.NONE, 1500),
                new Item(235, "Emerald harpoon", false, new Stats(), new SkillRequirement(), "A platinum harpoon decorated with an emerald.", false, false, EquipmentType.NONE, 1500),
                new Item(236, "Sapphire harpoon", false, new Stats(), new SkillRequirement(), "A platinum harpoon decorated with a sapphire.", false, false, EquipmentType.NONE, 1500),
                new Item(237, "Wood arrow on a rope", false, new Stats(), new SkillRequirement(), "A shabby wooden arrow on a rope.", false, false, EquipmentType.NONE, 10),
                new Item(238, "Bronze arrow on a rope", false, new Stats(), new SkillRequirement(), "A bronze arrow on a rope.", false, false, EquipmentType.NONE, 50),
                new Item(239, "Silver arrow on a rope", false, new Stats(), new SkillRequirement(), "A silver arrow on a rope. cool.", false, false, EquipmentType.NONE, 100),
                new Item(240, "Gold arrow on a rope", false, new Stats(), new SkillRequirement(), "A gold arrow on a rope. epic.", false, false, EquipmentType.NONE, 200),
                new Item(241, "Platinum arrow on a rope", false, new Stats(), new SkillRequirement(), "A platinum arrow on a rope. wicked.", false, false, EquipmentType.NONE, 500),
                new Item(242, "Ruby arrow on a rope", false, new Stats(), new SkillRequirement(), "A platinum arrow on a rope decorated with a ruby.", false, false, EquipmentType.NONE, 1500),
                new Item(243, "Emerald arrow on a rope", false, new Stats(), new SkillRequirement(), "A platinum arrow on a rope decorated with an emerald.", false, false, EquipmentType.NONE, 1500),
                new Item(244, "Sapphire arrow on a rope", false, new Stats(), new SkillRequirement(), "A platinum arrow on a rope decorated with a sapphire.", false, false, EquipmentType.NONE, 1500),
                new Item(245, "Fishing bait", true, new Stats(), new SkillRequirement(), "Bait used for catching fish, when they are desperate enough to bite a hook.", false, false, EquipmentType.NONE, 5),
                new Item(246, "Grubs", true, new Stats(), new SkillRequirement(), "Grubbies! saltwater fish love these.", false, false, EquipmentType.NONE, 10),
                new Item(247, "Worms", true, new Stats(), new SkillRequirement(), "Yummy, delicous worms! freshwater fish love these.", false, false, EquipmentType.NONE, 15),
                new Item(248, "Terrarium", true, new Stats(), new SkillRequirement(), "A little rectangular glass box used for breeding disgusting insects like grubs and worms.", false, false, EquipmentType.NONE, 100),
                new Item(249, "Bass", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(250, "Esox", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(251, "Catfish", true, new Stats(), new SkillRequirement(), "Large freshwater fish, can also be found on the internet.", false, false, EquipmentType.NONE, 100),
                new Item(252, "Walleye", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(253, "Muskellunge", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(254, "Tuna", true, new Stats(), new SkillRequirement(), "Large saltwater fish.", false, false, EquipmentType.NONE, 100),
                new Item(255, "Tarpon", true, new Stats(), new SkillRequirement(), "Large saltwater fish.", false, false, EquipmentType.NONE, 100),
                new Item(256, "Marlin", true, new Stats(), new SkillRequirement(), "Large saltwater fish with a massive nose.", false, false, EquipmentType.NONE, 100),
                new Item(257, "Red drum", true, new Stats(), new SkillRequirement(), "Small saltwater fish.", false, false, EquipmentType.NONE, 20),
                new Item(258, "Salmon", true, new Stats(), new SkillRequirement(), "Medium-sized saltwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(259, "Seed dibber", false, new Stats(), new SkillRequirement(), "A useful tool, commonly used to make holes with.", false, false, EquipmentType.NONE, 10),
                new Item(260, "Spade", false, new Stats(), new SkillRequirement(), "A useful tool, commonly used to dig up plants or treasure!", false, false, EquipmentType.NONE, 10),
                new Item(261, "Compost", true, new Stats(), new SkillRequirement(), "Literal cow shit, apparently it makes your plants grow faster.", false, false, EquipmentType.NONE, 50),
                new Item(262, "Watering can", false, new Stats(), new SkillRequirement(), "A watering can is most commonly used for watering plants.", false, false, EquipmentType.NONE, 100),
                new Item(263, "Tomato seed", true, new Stats(), new SkillRequirement(), "If you put this in the ground and water it every day, a tomato plant will grow!", false, false, EquipmentType.NONE, 10),
                new Item(264, "Corn seed", true, new Stats(), new SkillRequirement(), "If you put this in the ground and water it every day, corn will grow!", false, false, EquipmentType.NONE, 15),
                new Item(265, "Lettuce seed", true, new Stats(), new SkillRequirement(), "If you put this in the ground and water it every day, lettuce will grow!", false, false, EquipmentType.NONE, 20),
                new Item(266, "Onion seed", true, new Stats(), new SkillRequirement(), "If you put this in the ground and water it every day, onions will grow!", false, false, EquipmentType.NONE, 20),
                new Item(267, "Tomato", true, new Stats(), new SkillRequirement(), "Round, red and very juicy!", false, false, EquipmentType.NONE, 5),
                new Item(268, "Corn", true, new Stats(), new SkillRequirement(), "Corn gang.", false, false, EquipmentType.NONE, 10),
                new Item(269, "Lettuce", true, new Stats(), new SkillRequirement(), "Edible plants.", false, false, EquipmentType.NONE, 15),
                new Item(270, "Onion", true, new Stats(), new SkillRequirement(), "You could technically eat these raw.", false, false, EquipmentType.NONE, 15),
                new Item(271, "Berries", true, new Stats(), new SkillRequirement(), "Smash 'em together to make jam.", false, false, EquipmentType.NONE, 5),
                new Item(272, "Hay", true, new Stats(), new SkillRequirement(), "Dried up grass, animals love this.", false, false, EquipmentType.NONE, 10),
                new Item(273, "Animal medicine", true, new Stats(), new SkillRequirement(), "Only meant for animals, wesket!", false, false, EquipmentType.NONE, 100),
                new Item(274, "Shears", false, new Stats(), new SkillRequirement(), "You can shear sheep with this.", false, false, EquipmentType.NONE, 10),
                new Item(275, "Milk", true, new Stats(), new SkillRequirement(), "Came from a cows udders, think about that for a second.", false, false, EquipmentType.NONE, 25),
                new Item(276, "Goat milk", true, new Stats(), new SkillRequirement(), "This milk was intended to feed baby goats with, but you took it.", false, false, EquipmentType.NONE, 50),
                new Item(277, "Egg", true, new Stats(), new SkillRequirement(), "An egg.", false, false, EquipmentType.NONE, 10),
                new Item(278, "Wool", true, new Stats(), new SkillRequirement(), "Very soft.", false, false, EquipmentType.NONE, 10),
                new Item(279, "Cook's book", false, new Stats(), new SkillRequirement(), "It used to belong to the late town's cook, now it's yours.", false, false, EquipmentType.NONE, 1),
                new Item(280, "Burnt deer meat", true, new Stats(), new SkillRequirement(), "This meat has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE, 0),
                new Item(281, "Burnt fish", true, new Stats(), new SkillRequirement(), "This fish has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE, 0),
                new Item(282, "Burnt duck", true, new Stats(), new SkillRequirement(), "This duck has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE, 0),
                new Item(283, "Burnt goose", true, new Stats(), new SkillRequirement(), "This goose has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE, 0),
                new Item(284, "Burnt rabbit", true, new Stats(), new SkillRequirement(), "This rabbit has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE, 0),
                new Item(285, "Burnt bird", true, new Stats(), new SkillRequirement(), "This bird has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE, 0),
                new Item(286, "Over-fried egg", true, new Stats(), new SkillRequirement(), "Some would just call it burnt.", false, false, EquipmentType.NONE, 0),
                new Item(287, "Deer with tomato", false, new Stats(), new SkillRequirement(), "The tomatoes look homegrown, it would be disrespectful not to eat them.", false, false, EquipmentType.NONE, 100),
                new Item(288, "Deer with corn", false, new Stats(), new SkillRequirement(), "Seems like a solid meal.", false, false, EquipmentType.NONE, 100),
                new Item(289, "Deer with lettuce", false, new Stats(), new SkillRequirement(), "Teasing the dead deer with his favorite grass.", false, false, EquipmentType.NONE, 100),
                new Item(290, "Deer with onion", false, new Stats(), new SkillRequirement(), "Deer and onion.", false, false, EquipmentType.NONE, 100),
                new Item(291, "Deer with cheese", false, new Stats(), new SkillRequirement(), "A lump of deer with some molten cheese on top.", false, false, EquipmentType.NONE, 100),
                new Item(292, "Deer with milk", false, new Stats(), new SkillRequirement(), "The milk brings a creamy element to the meal.", false, false, EquipmentType.NONE, 100),
                new Item(293, "Burnt deer with tomato", true, new Stats(), new SkillRequirement(), "The meal looks burnt, it would alright not to eat this.", false, false, EquipmentType.NONE, 0),
                new Item(294, "Burnt deer with corn", true, new Stats(), new SkillRequirement(), "Seems like a burnt meal.", false, false, EquipmentType.NONE, 0),
                new Item(295, "Burnt deer with lettuce", true, new Stats(), new SkillRequirement(), "Teasing the burnt dead deer with his favorite grass.", false, false, EquipmentType.NONE, 0),
                new Item(296, "Burnt deer with onion", true, new Stats(), new SkillRequirement(), "Burnt deer and onion.", false, false, EquipmentType.NONE, 0),
                new Item(297, "Burnt deer with cheese", true, new Stats(), new SkillRequirement(), "A burnt lump of deer with some molten cheese on top.", false, false, EquipmentType.NONE, 0),
                new Item(298, "Burnt deer with milk", true, new Stats(), new SkillRequirement(), "The milk brings a creamy element to the meal. Unfortunately the meal needs more than that to be saved.", false, false, EquipmentType.NONE, 0),
                new Item(299, "Duck with tomato", false, new Stats(), new SkillRequirement(), "Not a big meal, but it should do the job.", false, false, EquipmentType.NONE, 100),
                new Item(300, "Duck with corn", false, new Stats(), new SkillRequirement(), "A lovely conbination.", false, false, EquipmentType.NONE, 100),
                new Item(301, "Duck with lettuce", false, new Stats(), new SkillRequirement(), "The lettuce makes the duck feel at home one last time.", false, false, EquipmentType.NONE, 100),
                new Item(302, "Duck with onion", false, new Stats(), new SkillRequirement(), "Duck and onion.", false, false, EquipmentType.NONE, 100),
                new Item(303, "Duck with cheese", false, new Stats(), new SkillRequirement(), "You'd better tone down the mouth watering, the duck might swim away.", false, false, EquipmentType.NONE, 100),
                new Item(304, "Duck with milk", false, new Stats(), new SkillRequirement(), "A daring combination.", false, false, EquipmentType.NONE, 100),
                new Item(305, "Burnt duck with tomato", true, new Stats(), new SkillRequirement(), "I don't think this'll do the job.", false, false, EquipmentType.NONE, 0),
                new Item(306, "Burnt duck with corn", true, new Stats(), new SkillRequirement(), "A true disappointment.", false, false, EquipmentType.NONE, 0),
                new Item(307, "Burnt duck with lettuce", true, new Stats(), new SkillRequirement(), "Must have reminded it of the warm summer days.", false, false, EquipmentType.NONE, 0),
                new Item(308, "Burnt duck with onion", true, new Stats(), new SkillRequirement(), "Burnt duck and onion.", false, false, EquipmentType.NONE, 0),
                new Item(309, "Burnt duck with cheese", true, new Stats(), new SkillRequirement(), "You ruined it.", false, false, EquipmentType.NONE, 0),
                new Item(310, "Burnt duck with milk", true, new Stats(), new SkillRequirement(), "I guess it didn't work out.", false, false, EquipmentType.NONE, 0),
                new Item(311, "Goose with tomato", false, new Stats(), new SkillRequirement(), "HONK.", false, false, EquipmentType.NONE, 100),
                new Item(312, "Goose with corn", false, new Stats(), new SkillRequirement(), "HONK HONK.", false, false, EquipmentType.NONE, 100),
                new Item(313, "Goose with lettuce", false, new Stats(), new SkillRequirement(), "HONK HONK HONK.", false, false, EquipmentType.NONE, 100),
                new Item(314, "Goose with onion", false, new Stats(), new SkillRequirement(), "Goose and onion.", false, false, EquipmentType.NONE, 100),
                new Item(315, "Goose with cheese", false, new Stats(), new SkillRequirement(), "HONK HONK HONK HONK.", false, false, EquipmentType.NONE, 100),
                new Item(316, "Goose with milk", false, new Stats(), new SkillRequirement(), "HONK x5.", false, false, EquipmentType.NONE, 100),
                new Item(317, "Burnt goose with tomato", true, new Stats(), new SkillRequirement(), "Sad honk.", false, false, EquipmentType.NONE, 0),
                new Item(318, "Burnt goose with corn", true, new Stats(), new SkillRequirement(), "Sad honk honk.", false, false, EquipmentType.NONE, 0),
                new Item(319, "Burnt goose with lettuce", true, new Stats(), new SkillRequirement(), "Sad honk honk honk.", false, false, EquipmentType.NONE, 0),
                new Item(320, "Burnt goose with onion", true, new Stats(), new SkillRequirement(), "Burnt goose and onion.", false, false, EquipmentType.NONE, 0),
                new Item(321, "Burnt goose with cheese", true, new Stats(), new SkillRequirement(), "Sad honk honk honk honk.", false, false, EquipmentType.NONE, 0),
                new Item(322, "Burnt goose with milk", true, new Stats(), new SkillRequirement(), "Sad honk x5.", false, false, EquipmentType.NONE, 0),
                new Item(323, "Rabbit with tomato", false, new Stats(), new SkillRequirement(), "Can't tell if it's a regular rabbit or a hare.. they're the same really.", false, false, EquipmentType.NONE, 100),
                new Item(324, "Rabbit with corn", false, new Stats(), new SkillRequirement(), "Who thought this was a good idea?", false, false, EquipmentType.NONE, 100),
                new Item(325, "Rabbit with lettuce", false, new Stats(), new SkillRequirement(), "Are you trying to feed a dead rabbit?", false, false, EquipmentType.NONE, 100),
                new Item(326, "Rabbit with onion", false, new Stats(), new SkillRequirement(), "Rabbit and onion.", false, false, EquipmentType.NONE, 100),
                new Item(327, "Rabbit with cheese", false, new Stats(), new SkillRequirement(), "This rabbit has a yellow blanket.", false, false, EquipmentType.NONE, 100),
                new Item(328, "Rabbit with milk", false, new Stats(), new SkillRequirement(), "Looks like it drowned :(.", false, false, EquipmentType.NONE, 100),
                new Item(329, "Burnt rabbit with tomato", true, new Stats(), new SkillRequirement(), "Burnt rabbit and hare still look the same.", false, false, EquipmentType.NONE, 0),
                new Item(330, "Burnt rabbit with corn", true, new Stats(), new SkillRequirement(), "I told you it was a bad idea.", false, false, EquipmentType.NONE, 0),
                new Item(331, "Burnt rabbit with lettuce", true, new Stats(), new SkillRequirement(), "Not surprised you burned that one.", false, false, EquipmentType.NONE, 0),
                new Item(332, "Burnt rabbit with onion", true, new Stats(), new SkillRequirement(), "Burnt rabbit and onion.", false, false, EquipmentType.NONE, 0),
                new Item(333, "Burnt rabbit with cheese", true, new Stats(), new SkillRequirement(), "No yellow blanket for this fella.", false, false, EquipmentType.NONE, 0),
                new Item(334, "Burnt rabbit with milk", true, new Stats(), new SkillRequirement(), "Very sad indeed.", false, false, EquipmentType.NONE, 0),
                new Item(335, "Fish with tomato", false, new Stats(), new SkillRequirement(), "Not very appealing.", false, false, EquipmentType.NONE, 100),
                new Item(336, "Fish with corn", false, new Stats(), new SkillRequirement(), "As in 'A plate with fish and corn', not 'fishing with corn as bait'.", false, false, EquipmentType.NONE, 100),
                new Item(337, "Fish with lettuce", false, new Stats(), new SkillRequirement(), "How creative.", false, false, EquipmentType.NONE, 100),
                new Item(338, "Fish with onion", false, new Stats(), new SkillRequirement(), "Fish and onion.", false, false, EquipmentType.NONE, 100),
                new Item(339, "Fish with cheese", false, new Stats(), new SkillRequirement(), "Not to be confused with fish and chips.", false, false, EquipmentType.NONE, 100),
                new Item(340, "Fish with milk", false, new Stats(), new SkillRequirement(), "One last swim.", false, false, EquipmentType.NONE, 100),
                new Item(341, "Burnt fish with tomato", true, new Stats(), new SkillRequirement(), "Appalling.", false, false, EquipmentType.NONE, 0),
                new Item(342, "Burnt fish with corn", true, new Stats(), new SkillRequirement(), "Try paying more attention next time.", false, false, EquipmentType.NONE, 0),
                new Item(343, "Burnt fish with lettuce", true, new Stats(), new SkillRequirement(), "Definitely original.", false, false, EquipmentType.NONE, 0),
                new Item(344, "Burnt fish with onion", true, new Stats(), new SkillRequirement(), "Burnt fish and onion.", false, false, EquipmentType.NONE, 0),
                new Item(345, "Burnt fish with cheese", true, new Stats(), new SkillRequirement(), "Atrocious.", false, false, EquipmentType.NONE, 0),
                new Item(346, "Burnt fish with milk", true, new Stats(), new SkillRequirement(), "Read the name, what enlightenment did you expect to find here?.", false, false, EquipmentType.NONE, 0),
                new Item(347, "Fried egg with tomato", false, new Stats(), new SkillRequirement(), "Great for breakfast.", false, false, EquipmentType.NONE, 100),
                new Item(348, "Fried egg with corn", false, new Stats(), new SkillRequirement(), "Great for lunch.", false, false, EquipmentType.NONE, 100),
                new Item(349, "Fried egg with lettuce", false, new Stats(), new SkillRequirement(), "Great for dinner.", false, false, EquipmentType.NONE, 100),
                new Item(350, "Fried egg with onion", false, new Stats(), new SkillRequirement(), "Fried egg and onion", false, false, EquipmentType.NONE, 100),
                new Item(351, "Fried egg with cheese", false, new Stats(), new SkillRequirement(), "Great as snack", false, false, EquipmentType.NONE, 100),
                new Item(352, "Fried egg with milk", false, new Stats(), new SkillRequirement(), "Eat it whenever.", false, false, EquipmentType.NONE, 100),
                new Item(353, "Burnt Fried egg with tomato", true, new Stats(), new SkillRequirement(), "Not so great for breakfast.", false, false, EquipmentType.NONE, 0),
                new Item(354, "Burnt Fried egg with corn", true, new Stats(), new SkillRequirement(), "Not so great for lunch.", false, false, EquipmentType.NONE, 0),
                new Item(355, "Burnt Fried egg with lettuce", true, new Stats(), new SkillRequirement(), "Not so great for dinner", false, false, EquipmentType.NONE, 0),
                new Item(356, "Burnt Fried egg with onion", true, new Stats(), new SkillRequirement(), "Burnt egg and onion", false, false, EquipmentType.NONE, 0),
                new Item(357, "Burnt Fried egg with cheese", true, new Stats(), new SkillRequirement(), "Not so great as snack.", false, false, EquipmentType.NONE, 0),
                new Item(358, "Burnt Fried egg with milk", true, new Stats(), new SkillRequirement(), "Don't eat it.", false, false, EquipmentType.NONE, 0),
                new Item(359, "Egg salad", false, new Stats(), new SkillRequirement(), "An egg with some weeds or something.", false, false, EquipmentType.NONE, 100),
                new Item(360, "Cheese salad", false, new Stats(), new SkillRequirement(), "Healthy salad.", false, false, EquipmentType.NONE, 100),
                new Item(361, "Cheese", true, new Stats(), new SkillRequirement(), "This also came from a cow's udders indirectly.", false, false, EquipmentType.NONE, 100),
                new Item(362, "Goat cheese", true, new Stats(), new SkillRequirement(), "Significantly different from a cow's cheese.", false, false, EquipmentType.NONE, 100),
                new Item(363, "Jam", true, new Stats(), new SkillRequirement(), "A bunch of berries mashed together.", false, false, EquipmentType.NONE, 25),
                new Item(364, "Wool carpet", true, new Stats(), new SkillRequirement(), "A very soft carpet.", false, false, EquipmentType.NONE, 50),
                new Item(365, "Wool blanket", true, new Stats(), new SkillRequirement(), "A very soft blanket.", false, false, EquipmentType.NONE, 50),
                new Item(366, "Bronze dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of bronze.", false, true, EquipmentType.OFFHAND, 10),
                new Item(367, "Silver dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of silver.", false, true, EquipmentType.OFFHAND, 100),
                new Item(368, "Gold dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of gold.", false, true, EquipmentType.OFFHAND, 200),
                new Item(369, "Platinum dagger", false, new Stats(), new SkillRequirement(), "A regular dagger made out of platinum.", false, true, EquipmentType.OFFHAND, 500),
                new Item(370, "Ruby dagger", false, new Stats(), new SkillRequirement(), "A dagger made out of platinum. There's a ruby in the rain-guard.", false, true, EquipmentType.OFFHAND, 1500),
                new Item(371, "Emerald dagger", false, new Stats(), new SkillRequirement(), "A dagger made out of platinum. There's an emerald in the rain-guard.", false, true, EquipmentType.OFFHAND, 1500),
                new Item(372, "Sapphire dagger", false, new Stats(), new SkillRequirement(), "A dagger made out of platinum. There's a sapphire in the rain-guard.", false, true, EquipmentType.OFFHAND, 1500),
                new Item(373, "Raw bass", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 20),
                new Item(374, "Raw esox", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 20),
                new Item(375, "Raw catfish", true, new Stats(), new SkillRequirement(), "Large freshwater fish, can also be found on the internet.", false, false, EquipmentType.NONE, 50),
                new Item(376, "Raw walleye", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 20),
                new Item(377, "Raw muskellunge", true, new Stats(), new SkillRequirement(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE, 20),
                new Item(378, "Raw tuna", true, new Stats(), new SkillRequirement(), "Large saltwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(379, "Raw tarpon", true, new Stats(), new SkillRequirement(), "Large saltwater fish.", false, false, EquipmentType.NONE, 50),
                new Item(380, "Raw marlin", true, new Stats(), new SkillRequirement(), "Large saltwater fish with a massive nose.", false, false, EquipmentType.NONE, 50),
                new Item(381, "Raw red drum", true, new Stats(), new SkillRequirement(), "Small saltwater fish.", false, false, EquipmentType.NONE, 10),
                new Item(382, "Raw salmon", true, new Stats(), new SkillRequirement(), "Medium-sized saltwater fish.", false, false, EquipmentType.NONE, 20),
                new Item(383, "Rope", true, new Stats(), new SkillRequirement(), "A length of rope made out of hair, yuck.", false, false, EquipmentType.NONE, 10),
                new Item(384, "Coins", true, new Stats(), new SkillRequirement(), "Some type of currency.", false, false, EquipmentType.NONE, 1),
                new Item(385, "Bird with tomato", false, new Stats(), new SkillRequirement(), "Italian style bird", false, false, EquipmentType.NONE, 100),
                new Item(386, "Bird with corn", false, new Stats(), new SkillRequirement(), "American style bird.", false, false, EquipmentType.NONE, 100),
                new Item(387, "Bird with lettuce", false, new Stats(), new SkillRequirement(), "European style bird.", false, false, EquipmentType.NONE, 100),
                new Item(388, "Bird with onion", false, new Stats(), new SkillRequirement(), "Bird and onion.", false, false, EquipmentType.NONE, 100),
                new Item(389, "Bird with cheese", false, new Stats(), new SkillRequirement(), "Bird covered in cheese.", false, false, EquipmentType.NONE, 100),
                new Item(390, "Bird with milk", false, new Stats(), new SkillRequirement(), "Bird with a creamy taste.", false, false, EquipmentType.NONE, 100),
                new Item(391, "Burnt bird with tomato", true, new Stats(), new SkillRequirement(), "The mafia got to him.", false, false, EquipmentType.NONE, 0),
                new Item(392, "Burnt bird with corn", true, new Stats(), new SkillRequirement(), "Nice and crunchy.", false, false, EquipmentType.NONE, 0),
                new Item(393, "Burnt bird with lettuce", true, new Stats(), new SkillRequirement(), "Unlucky cook.", false, false, EquipmentType.NONE, 0),
                new Item(394, "Burnt bird with onion", true, new Stats(), new SkillRequirement(), "Burnt bird and onion.", false, false, EquipmentType.NONE, 0),
                new Item(395, "Burnt bird with cheese", true, new Stats(), new SkillRequirement(), "Burnt bird covered in cheese.", false, false, EquipmentType.NONE, 0),
                new Item(396, "Burnt bird with milk", true, new Stats(), new SkillRequirement(), "Bird with a burnt taste.", false, false, EquipmentType.NONE, 0),
                new Item(397, "Fried egg", false, new Stats(), new SkillRequirement(), "Sunny side up.", false, false, EquipmentType.NONE, 0),
                new Item(398, "Tito's package", false, new Stats(), new SkillRequirement(), "I wonder what is in here...", true, false, EquipmentType.NONE, 0),
                new Item(399, "Laysee's ladder", false, new Stats(), new SkillRequirement(), "That goes up pretty high.", true, false, EquipmentType.NONE, 0),
                new Item(400, "Blake's milk", false, new Stats(), new SkillRequirement(), "Good for your bones.", true, false, EquipmentType.NONE, 0),
                new Item(401, "Jake's Blake's spoon", false, new Stats(), new SkillRequirement(), "Filty thief!", true, false, EquipmentType.NONE, 0),
                new Item(402, "Tomato permit", false, new Stats(), new SkillRequirement(), "This will finally allow Jake to farm tomatoes!", true, false, EquipmentType.NONE, 0),
                new Item(403, "Clara's answer", false, new Stats(), new SkillRequirement(), "He's not gonna be happy...", true, false, EquipmentType.NONE, 0),
                new Item(404, "Susan's poem", false, new Stats(), new SkillRequirement(), "Beautifully written.", true, false, EquipmentType.NONE, 0),
                new Item(405, "Sword's ring", false, new Stats(), new SkillRequirement(), "Yuck.", true , false, EquipmentType.NONE, 0),
                new Item(406, "Finch's marlin", false, new Stats(), new SkillRequirement(), "Big fish, bit stinky, but big.", true, false, EquipmentType.NONE, 0)
            };

            EquipmentArray = new EquipmentItemMultiArray[items.Count];
            InventoryIcon = new Sprite[items.Count];
            for (int i = 0; i < items.Count; i++)
            {
                EquipmentArray[i] = new EquipmentItemMultiArray();
                EquipmentArray[i].EquipSprites = new Sprite[4];
                for (int j = 0; j < EquipmentArray[i].EquipSprites.Length; j++)
                {
                    InventoryIcon[i] = Resources.Load<Sprite>($"Item/{i}/item_{i}");
                    if(InventoryIcon[i] == null)
                        InventoryIcon[i] = Resources.Load<Sprite>($"Item/{i}/item_{i}_0");
                    EquipmentArray[i].EquipSprites[j] = Resources.Load<Sprite>($"Item/{i}/item_{i}_{j}");
                    ((Item)items[i]).SetSprites(InventoryIcon[i], EquipmentArray[i]);
                }
            }

            //for(int i = 0; i < InventoryIcon.Length; i++)
            //    ((Item)items[i]).SetSprites(InventoryIcon[i], EquipmentArray[i]);



            CrLogger.Log(this, "The item database was built succesfully");
            CrLogger.Log(this, "Now allows for initialisation of: shops database");
            GetComponent<ShopDatabase>().BuildDatabase();
            GetComponent<ConsumableDatabase>().BuildDatabase();
        }

        /// <summary>
        /// returns a new instance of an item with given id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Item GetItem(int id)
        {
            return new Item(items.Where(i => i.Id == id).FirstOrDefault() as Item);
        }

        /// <summary>
        /// returns a new instance the item of id and sets the amount to amount
        /// </summary>
        /// <param name="id"></param>
        /// <param name="amount"></param>
        /// <returns></returns>
        public Item GetItem(int id, int amount)
        {
            Item it = GetItem(id);//new Item(GetItem(id));
            it.SetAmount(amount);
            return it;
        }
    }
}
