using Assets.Scripts.item;
using Assets.Scripts.logger;
using Assets.Scripts.node;
using Assets.Scripts.stats;
using Assets.Scripts.util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace Assets.Scripts.databases
{
    /// <summary>
    /// Items stored in this game
    /// </summary>
    public class ItemDatabase : CRDatabase
    {
        /// <summary>
        /// The inventory icons
        /// </summary>
        private Sprite[] InventoryIcon;
        
        /// <summary>
        /// Builds the item database
        /// </summary>
        public override void BuildDatabase()
        {
            CrLogger.Log(this, "Building item database...");

            items = new List<DbElement>()
            {
                new Item(0, "Hedgehog plushie", false, new Stats(), new Skills(), "A nice plushie, it says POG on the label.", false, true, EquipmentType.MAINHAND),
                new Item(1, "Rat plushie", false, new Stats(), new Skills(), "When you squeeze it, it squeeks!", false, true, EquipmentType.MAINHAND),
                new Item(2, "Cat plushie", false, new Stats(), new Skills(), "Meeeeeeeow", false, true, EquipmentType.MAINHAND),
                new Item(3, "Dog plushie", false, new Stats(), new Skills(), "He doesn't do much but he's a good boy.", false, true, EquipmentType.MAINHAND),
                new Item(4, "Wood sword", false, new Stats(), new Skills(), "a regular sword made out of wood.", false, true, EquipmentType.MAINHAND),
                new Item(5, "Bronze sword", false, new Stats(), new Skills(), "a regular sword made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(6, "Silver sword", false, new Stats(), new Skills(), "a regular sword made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(7, "Gold sword", false, new Stats(), new Skills(), "a regular sword made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(8, "Platinum sword", false, new Stats(), new Skills(), "a regular sword made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(9, "Ruby sword", false, new Stats(), new Skills(), "a sword made out of platinum. There's a ruby in the rain-guard.", false, true, EquipmentType.MAINHAND),
                new Item(10, "Emerald sword", false, new Stats(), new Skills(), "a sword made out of platinum. There's an emerald in the rain-guard.", false, true, EquipmentType.MAINHAND),
                new Item(11, "Sapphire sword", false, new Stats(), new Skills(), "a sword made out of platinum. There's a sapphire in the rain-guard.", false, true, EquipmentType.MAINHAND),
                new Item(12, "Wood shield", false, new Stats(), new Skills(), "a regular shield made out of wood.", false, true, EquipmentType.OFFHAND),
                new Item(13, "Bronze shield", false, new Stats(), new Skills(), "a regular shield made out of bronze.", false, true, EquipmentType.OFFHAND),
                new Item(14, "Silver shield", false, new Stats(), new Skills(), "a regular shield made out of silver.", false, true, EquipmentType.OFFHAND),
                new Item(15, "Gold shield", false, new Stats(), new Skills(), "a regular shield made out of gold.", false, true, EquipmentType.OFFHAND),
                new Item(16, "Platinum shield", false, new Stats(), new Skills(), "a regular shield made out of platinum.", false, true, EquipmentType.OFFHAND),
                new Item(17, "Ruby shield", false, new Stats(), new Skills(), "a shield made out of platinum. There's a ruby at the center of the disc.", false, true, EquipmentType.OFFHAND),
                new Item(18, "Emerald shield", false, new Stats(), new Skills(), "a shield made out of platinum. There's an emerald at the center of the disc.", false, true, EquipmentType.OFFHAND),
                new Item(19, "Sapphire shield", false, new Stats(), new Skills(), "a shield made out of platinum. There's a sapphire at the center of the disc.", false, true, EquipmentType.OFFHAND),
                new Item(20, "Wood dagger", false, new Stats(), new Skills(), "a regular dagger made out of wood.", false, true, EquipmentType.MAINHAND),
                new Item(21, "Bronze dagger", false, new Stats(), new Skills(), "a regular dagger made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(22, "Silver dagger", false, new Stats(), new Skills(), "a regular dagger made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(23, "Gold dagger", false, new Stats(), new Skills(), "a regular dagger made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(24, "Platinum dagger", false, new Stats(), new Skills(), "a regular dagger made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(25, "Ruby dagger", false, new Stats(), new Skills(), "a dagger made out of platinum. There's a ruby in the rain-guard.", false, true, EquipmentType.MAINHAND),
                new Item(26, "Emerald dagger", false, new Stats(), new Skills(), "a dagger made out of platinum. There's an emerald in the rain-guard.", false, true, EquipmentType.MAINHAND),
                new Item(27, "Sapphire dagger", false, new Stats(), new Skills(), "a dagger made out of platinum. There's a sapphire in the rain-guard.", false, true, EquipmentType.MAINHAND),
                new Item(28, "Wood greataxe", false, new Stats(), new Skills(), "a regular greataxe made out of wood.", false, true, EquipmentType.MAINHAND),
                new Item(29, "Bronze greataxe", false, new Stats(), new Skills(), "a regular greataxe made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(30, "Silver greataxe", false, new Stats(), new Skills(), "a regular greataxe made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(31, "Gold greataxe", false, new Stats(), new Skills(), "a regular greataxe made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(32, "Platinum greataxe", false, new Stats(), new Skills(), "a regular greataxe made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(33, "Ruby greataxe", false, new Stats(), new Skills(), "a greataxe made out of platinum. There's a ruby inbetween the blades.", false, true, EquipmentType.MAINHAND),
                new Item(34, "Emerald greataxe", false, new Stats(), new Skills(), "a greataxe made out of platinum. There's an emerald inbetween the blades.", false, true, EquipmentType.MAINHAND),
                new Item(35, "Sapphire greataxe", false, new Stats(), new Skills(), "a greataxe made out of platinum. There's a sapphire inbetween the blades.", false, true, EquipmentType.MAINHAND),
                new Item(36, "Wood scythe", false, new Stats(), new Skills(), "a regular scythe made out of wood.", false, true, EquipmentType.MAINHAND),
                new Item(37, "Bronze scythe", false, new Stats(), new Skills(), "a regular scythe made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(38, "Silver scythe", false, new Stats(), new Skills(), "a regular scythe made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(39, "Gold scythe", false, new Stats(), new Skills(), "a regular scythe made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(40, "Platinum scythe", false, new Stats(), new Skills(), "a regular scythe made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(41, "Ruby scythe", false, new Stats(), new Skills(), "a scythe made out of platinum. The attachment ring is decorated with a ruby.", false, true, EquipmentType.MAINHAND),
                new Item(42, "Emerald scythe", false, new Stats(), new Skills(), "a scythe made out of platinum. The attachment ring is decorated with an emerald.", false, true, EquipmentType.MAINHAND),
                new Item(43, "Sapphire scythe", false, new Stats(), new Skills(), "a scythe made out of platinum. The attachment ring is decorated with a sapphire.", false, true, EquipmentType.MAINHAND),
                new Item(44, "Bronze helmet", false, new Stats(), new Skills(), "a regular helmet made out of bronze.", false, true, EquipmentType.HEAD),
                new Item(45, "Silver helmet", false, new Stats(), new Skills(), "a regular helmet made out of silver.", false, true, EquipmentType.HEAD),
                new Item(46, "Gold helmet", false, new Stats(), new Skills(), "a regular helmet made out of gold.", false, true, EquipmentType.HEAD),
                new Item(47, "Platinum helmet", false, new Stats(), new Skills(), "a regular helmet made out of platinum.", false, true, EquipmentType.HEAD),
                new Item(48, "Ruby helmet", false, new Stats(), new Skills(), "a helmet made out of platinum. It is decorated with a ruby.", false, true, EquipmentType.HEAD),
                new Item(49, "Emerald helmet", false, new Stats(), new Skills(), "a helmet made out of platinum. It is decorated with an emerald.", false, true, EquipmentType.HEAD),
                new Item(50, "Sapphire helmet", false, new Stats(), new Skills(), "a helmet made out of platinum. It is decorated with a sapphire.", false, true, EquipmentType.HEAD),
                new Item(51, "Bronze chestplate", false, new Stats(), new Skills(), "a regular chestplate made out of bronze.", false, true, EquipmentType.TORSO),
                new Item(52, "Silver chestplate", false, new Stats(), new Skills(), "a regular chestplate made out of silver.", false, true, EquipmentType.TORSO),
                new Item(53, "Gold chestplate", false, new Stats(), new Skills(), "a regular chestplate made out of gold.", false, true, EquipmentType.TORSO),
                new Item(54, "Platinum chestplate", false, new Stats(), new Skills(), "a regular chestplate made out of platinum.", false, true, EquipmentType.TORSO),
                new Item(55, "Ruby chestplate", false, new Stats(), new Skills(), "a chestplate made out of platinum. It is decorated with a ruby.", false, true, EquipmentType.TORSO),
                new Item(56, "Emerald chestplate", false, new Stats(), new Skills(), "a chestplate made out of platinum. It is decorated with an emerald.", false, true, EquipmentType.TORSO),
                new Item(57, "Sapphire chestplate", false, new Stats(), new Skills(), "a chestplate made out of platinum. It is decorated with a sapphire.", false, true, EquipmentType.TORSO),
                new Item(58, "Bronze legs", false, new Stats(), new Skills(), "a regular pair of legs, made out of bronze.", false, true, EquipmentType.LEGS),
                new Item(59, "Silver legs", false, new Stats(), new Skills(), "a regular pair of legs, made out of silver.", false, true, EquipmentType.LEGS),
                new Item(60, "Gold legs", false, new Stats(), new Skills(), "a regular pair of legs, made out of gold.", false, true, EquipmentType.LEGS),
                new Item(61, "Platinum legs", false, new Stats(), new Skills(), "a regular pair of legs, made out of platinum.", false, true, EquipmentType.LEGS),
                new Item(62, "Ruby legs", false, new Stats(), new Skills(), "a pair of legs made out of platinum. They're decorated with a ruby.", false, true, EquipmentType.LEGS),
                new Item(63, "Emerald legs", false, new Stats(), new Skills(), "a pair of legs made out of platinum. They're decorated with an emerald.", false, true, EquipmentType.LEGS),
                new Item(64, "Sapphire legs", false, new Stats(), new Skills(), "a pair of legs made out of platinum. They're decorated with a sapphire.", false, true, EquipmentType.LEGS),
                new Item(65, "Bronze boots", false, new Stats(), new Skills(), "a regular pair of boots made out of bronze.", false, true, EquipmentType.FEET),
                new Item(66, "Silver boots", false, new Stats(), new Skills(), "a regular pair of boots made out of silver.", false, true, EquipmentType.FEET),
                new Item(67, "Gold boots", false, new Stats(), new Skills(), "a regular pair of boots made out of gold.", false, true, EquipmentType.FEET),
                new Item(68, "Platinum boots", false, new Stats(), new Skills(), "a regular pair of boots made out of platinum.", false, true, EquipmentType.FEET),
                new Item(69, "Ruby boots", false, new Stats(), new Skills(), "a pair of boots made out of platinum. The nose is decorated with a ruby.", false, true, EquipmentType.FEET),
                new Item(70, "Emerald boots", false, new Stats(), new Skills(), "a boots made out of platinum. The nose is decorated with an emerald.", false, true, EquipmentType.FEET),
                new Item(71, "Sapphire boots", false, new Stats(), new Skills(), "a boots made out of platinum. The nose is decorated with a sapphire.", false, true, EquipmentType.FEET),
                new Item(72, "Ruby amulet", false, new Stats(), new Skills(), "an amulet made of gold, with a beatiful ruby on it.", false, true, EquipmentType.AMULET),
                new Item(73, "Emerald amulet", false, new Stats(), new Skills(), "an amulet made of gold, with a beatiful emerald on it.", false, true, EquipmentType.AMULET),
                new Item(74, "Sapphire amulet", false, new Stats(), new Skills(), "a an amulet made of gold, with a beatiful sapphire on it.", false, true, EquipmentType.AMULET),
                new Item(75, "Rock", true, new Stats(), new Skills(), "a light rock that can easily gain attention from someone by being thrown at them.", false, true, EquipmentType.AMMO),
                new Item(76, "Wood bow", false, new Stats(), new Skills(), "a regular bow made out of Wood.", false, true, EquipmentType.MAINHAND),
                new Item(77, "Bronze bow", false, new Stats(), new Skills(), "a regular bow made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(78, "Silver bow", false, new Stats(), new Skills(), "a regular bow made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(79, "Gold bow", false, new Stats(), new Skills(), "a regular bow made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(80, "Platinum bow", false, new Stats(), new Skills(), "a regular bow made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(81, "Ruby bow", false, new Stats(), new Skills(), "a bow made out of platinum. It's decorated with a ruby close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(82, "Emerald bow", false, new Stats(), new Skills(), "a bow made out of platinum. It's decorated with an emerald close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(83, "Sapphire bow", false, new Stats(), new Skills(), "a bow made out of platinum. It's decorated with a sapphire close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(84, "Wood crossbow", false, new Stats(), new Skills(), "a regular crossbow made out of Wood.", false, true, EquipmentType.MAINHAND),
                new Item(85, "Bronze crossbow", false, new Stats(), new Skills(), "a regular crossbow made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(86, "Silver crossbow", false, new Stats(), new Skills(), "a regular crossbow made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(87, "Gold crossbow", false, new Stats(), new Skills(), "a regular crossbow made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(88, "Platinum crossbow", false, new Stats(), new Skills(), "a regular crossbow made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(89, "Ruby crossbow", false, new Stats(), new Skills(), "a crossbow made out of platinum. It's stock is decorated with a ruby.", false, true, EquipmentType.MAINHAND),
                new Item(90, "Emerald crossbow", false, new Stats(), new Skills(), "a crossbow made out of platinum. It's stock is decorated with an emerald.", false, true, EquipmentType.MAINHAND),
                new Item(91, "Sapphire crossbow", false, new Stats(), new Skills(), "a crossbow made out of platinum. It's stock is decorated with a sapphire.", false, true, EquipmentType.MAINHAND),
                new Item(92, "Wood shortbow", false, new Stats(), new Skills(), "a regular shortbow made out of Wood.", false, true, EquipmentType.MAINHAND),
                new Item(93, "Bronze shortbow", false, new Stats(), new Skills(), "a regular shortbow made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(94, "Silver shortbow", false, new Stats(), new Skills(), "a regular shortbow made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(95, "Gold shortbow", false, new Stats(), new Skills(), "a regular shortbow made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(96, "Platinum shortbow", false, new Stats(), new Skills(), "a regular shortbow made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(97, "Ruby shortbow", false, new Stats(), new Skills(), "a shortbow made out of platinum. It's decorated with a ruby close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(98, "Emerald shortbow", false, new Stats(), new Skills(), "a shortbow made out of platinum. It's decorated with an emerald close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(99, "Sapphire shortbow", false, new Stats(), new Skills(), "a shortbow made out of platinum. It's decorated with a sapphire close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(100, "Wood longbow", false, new Stats(), new Skills(), "a regular longbow made out of Wood.", false, true, EquipmentType.MAINHAND),
                new Item(101, "Bronze longbow", false, new Stats(), new Skills(), "a regular longbow made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(102, "Silver longbow", false, new Stats(), new Skills(), "a regular longbow made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(103, "Gold longbow", false, new Stats(), new Skills(), "a regular longbow made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(104, "Platinum longbow", false, new Stats(), new Skills(), "a regular longbow made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(105, "Ruby longbow", false, new Stats(), new Skills(), "a longbow made out of platinum. It's decorated with a ruby close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(106, "Emerald longbow", false, new Stats(), new Skills(), "a longbow made out of platinum. It's decorated with an emerald close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(107, "Sapphire longbow", false, new Stats(), new Skills(), "a longbow made out of platinum. It's decorated with a sapphire close to the arrow rest.", false, true, EquipmentType.MAINHAND),
                new Item(108, "Wood chakram", true, new Stats(), new Skills(), "a regular chakram made out of Wood.", false, true, EquipmentType.MAINHAND),
                new Item(109, "Bronze chakram", true, new Stats(), new Skills(), "a regular chakram made out of bronze.", false, true, EquipmentType.MAINHAND),
                new Item(110, "Silver chakram", true, new Stats(), new Skills(), "a regular chakram made out of silver.", false, true, EquipmentType.MAINHAND),
                new Item(111, "Gold chakram", true, new Stats(), new Skills(), "a regular chakram made out of gold.", false, true, EquipmentType.MAINHAND),
                new Item(112, "Platinum chakram", true, new Stats(), new Skills(), "a regular chakram made out of platinum.", false, true, EquipmentType.MAINHAND),
                new Item(113, "Ruby chakram", true, new Stats(), new Skills(), "a chakram made out of platinum. It's handle is decorated with a ruby.", false, true, EquipmentType.MAINHAND),
                new Item(114, "Emerald chakram", true, new Stats(), new Skills(), "a chakram made out of platinum. It's handle is decorated with an emerald.", false, true, EquipmentType.MAINHAND),
                new Item(115, "Sapphire chakram", true, new Stats(), new Skills(), "a chakram made out of platinum. It's handle is decorated with a sapphire.", false, true, EquipmentType.MAINHAND),
                new Item(116, "Wood arrow", true, new Stats(), new Skills(), "a regular arrow made out of Wood.", false, true, EquipmentType.AMMO),
                new Item(117, "Bronze arrow", true, new Stats(), new Skills(), "a regular arrow, with a bronze tip.", false, true, EquipmentType.AMMO),
                new Item(118, "Silver arrow", true, new Stats(), new Skills(), "a regular arrow, with a silver tip.", false, true, EquipmentType.AMMO),
                new Item(119, "Gold arrow", true, new Stats(), new Skills(), "a regular arrow, with a gold tip.", false, true, EquipmentType.AMMO),
                new Item(120, "Platinum arrow", true, new Stats(), new Skills(), "a regular arrow, with a platinum tip.", false, true, EquipmentType.AMMO),
                new Item(121, "Ruby arrow", true, new Stats(), new Skills(), "an arrow made out of platinum. Its tip is made out of ruby.", false, true, EquipmentType.AMMO),
                new Item(122, "Emerald arrow", true, new Stats(), new Skills(), "an arrow made out of platinum. Its tip is made out of emerald.", false, true, EquipmentType.AMMO),
                new Item(123, "Sapphire arrow", true, new Stats(), new Skills(), "an arrow made out of platinum. Its tip is made out of sapphire.", false, true, EquipmentType.AMMO),
                new Item(125, "Wood bolt", true, new Stats(), new Skills(), "a regular bolt made out of Wood.", false, true, EquipmentType.AMMO),
                new Item(126, "Bronze bolt", true, new Stats(), new Skills(), "a regular bolt made out of bronze.", false, true, EquipmentType.AMMO),
                new Item(127, "Silver bolt", true, new Stats(), new Skills(), "a regular bolt made out of silver.", false, true, EquipmentType.AMMO),
                new Item(128, "Gold bolt", true, new Stats(), new Skills(), "a regular bolt made out of gold.", false, true, EquipmentType.AMMO),
                new Item(129, "Platinum bolt", true, new Stats(), new Skills(), "a regular bolt made out of platinum.", false, true, EquipmentType.AMMO),
                new Item(130, "Ruby bolt", true, new Stats(), new Skills(), "a bolt made out of platinum. Its tip is made out of ruby.", false, true, EquipmentType.AMMO),
                new Item(131, "Emerald bolt", true, new Stats(), new Skills(), "a bolt made out of platinum. Its tip is made out of emerald.", false, true, EquipmentType.AMMO),
                new Item(132, "Sapphire bolt", true, new Stats(), new Skills(), "a bolt made out of platinum. Its tip is made out of sapphire.", false, true, EquipmentType.AMMO),
                new Item(133, "Green leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a green deer.", false, true, EquipmentType.HEAD),
                new Item(134, "Turquoise leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a turquoise deer.", false, true, EquipmentType.HEAD),
                new Item(135, "Blue leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a blue deer.", false, true, EquipmentType.HEAD),
                new Item(136, "Purple leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a purple deer.", false, true, EquipmentType.HEAD),
                new Item(137, "Red leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a red deer.", false, true, EquipmentType.HEAD),
                new Item(138, "Black leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a black deer.", false, true, EquipmentType.HEAD),
                new Item(139, "White leather helmet", false, new Stats(), new Skills(), "a helmet made with the leather from a white deer.", false, true, EquipmentType.HEAD),
                new Item(140, "White leather helmet(r)", false, new Stats(), new Skills(), "a helmet made with the leather from a white deer. It's decorated with a big ruby.", false, true, EquipmentType.HEAD),
                new Item(141, "White leather helmet(e)", false, new Stats(), new Skills(), "a helmet made with the leather from a white deer. It's decorated with a big emerald.", false, true, EquipmentType.HEAD),
                new Item(142, "White leather helmet(s)", false, new Stats(), new Skills(), "a helmet made with the leather from a white deer. It's decorated with a big sapphire.", false, true, EquipmentType.HEAD),
                new Item(143, "Green leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a green deer.", false, true, EquipmentType.TORSO),
                new Item(144, "Turquoise leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a turquoise deer.", false, true, EquipmentType.TORSO),
                new Item(145, "Blue leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a blue deer.", false, true, EquipmentType.TORSO),
                new Item(146, "Purple leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a purple deer.", false, true, EquipmentType.TORSO),
                new Item(147, "Red leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a red deer.", false, true, EquipmentType.TORSO),
                new Item(148, "Black leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a black deer.", false, true, EquipmentType.TORSO),
                new Item(149, "White leather chestplate", false, new Stats(), new Skills(), "a chestplate made with the leather from a white deer.", false, true, EquipmentType.TORSO),
                new Item(150, "White leather chestplate(r)", false, new Stats(), new Skills(), "a chestplate made with the leather from a white deer. It's decorated with a big ruby.", false, true, EquipmentType.TORSO),
                new Item(151, "White leather chestplate(e)", false, new Stats(), new Skills(), "a chestplate made with the leather from a white deer. It's decorated with a big emerald.", false, true, EquipmentType.TORSO),
                new Item(152, "White leather chestplate(s)", false, new Stats(), new Skills(), "a chestplate made with the leather from a white deer. It's decorated with a big sapphire.", false, true, EquipmentType.TORSO),
                new Item(153, "Green leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a green deer.", false, true, EquipmentType.LEGS),
                new Item(154, "Turquoise leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a turquoise deer.", false, true, EquipmentType.LEGS),
                new Item(155, "Blue leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a blue deer.", false, true, EquipmentType.LEGS),
                new Item(156, "Purple leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a purple deer.", false, true, EquipmentType.LEGS),
                new Item(157, "Red leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a red deer.", false, true, EquipmentType.LEGS),
                new Item(158, "Black leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a black deer.", false, true, EquipmentType.LEGS),
                new Item(159, "White leather legs", false, new Stats(), new Skills(), "a pair of legs made with the leather from a white deer.", false, true, EquipmentType.LEGS),
                new Item(160, "White leather legs(r)", false, new Stats(), new Skills(), "a pair of legs made with the leather from a white deer. It's decorated with a ruby.", false, true, EquipmentType.LEGS),
                new Item(161, "White leather legs(e)", false, new Stats(), new Skills(), "a pair of legs made with the leather from a white deer. It's decorated with an emerald.", false, true, EquipmentType.LEGS),
                new Item(162, "White leather legs(s)", false, new Stats(), new Skills(), "a pair of legs made with the leather from a white deer. It's decorated with a sapphire.", false, true, EquipmentType.LEGS),
                new Item(163, "Green leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a green deer.", false, true, EquipmentType.FEET),
                new Item(164, "Turquoise leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a turquoise deer.", false, true, EquipmentType.FEET),
                new Item(165, "Blue leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a blue deer.", false, true, EquipmentType.FEET),
                new Item(166, "Purple leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a purple deer.", false, true, EquipmentType.FEET),
                new Item(167, "Red leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a red deer.", false, true, EquipmentType.FEET),
                new Item(168, "Black leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a black deer.", false, true, EquipmentType.FEET),
                new Item(169, "White leather boots", false, new Stats(), new Skills(), "a pair of boots made with the leather from a white deer.", false, true, EquipmentType.FEET),
                new Item(170, "White leather boots(r)", false, new Stats(), new Skills(), "a pair of boots made with the leather from a white deer. It's decorated with a ruby.", false, true, EquipmentType.FEET),
                new Item(171, "White leather boots(e)", false, new Stats(), new Skills(), "a pair of boots made with the leather from a white deer. It's decorated with an emerald.", false, true, EquipmentType.FEET),
                new Item(172, "White leather boots(s)", false, new Stats(), new Skills(), "a pair of boots made with the leather from a white deer. It's decorated with a sapphire.", false, true, EquipmentType.FEET),
                new Item(173, "Rodent trap", true, new Stats(), new Skills(), "Useful for catching rodents.", false, false, EquipmentType.NONE),
                new Item(174, "Bird trap", true, new Stats(), new Skills(), "Conveniently made with two spoons.", false, false, EquipmentType.NONE),
                new Item(175, "Deer bait", true, new Stats(), new Skills(), "The smell lures deer.", false, false, EquipmentType.NONE),
                new Item(176, "Game call", false, new Stats(), new Skills(), "an odd sounding instrument that mimics the sound of deer.", false, false, EquipmentType.NONE),
                new Item(177, "Green deer leather", true, new Stats(), new Skills(), "Leather that you took from a dead green deers body. you monster.", false, false, EquipmentType.NONE),
                new Item(178, "Turquoise deer leather", true, new Stats(), new Skills(), "Leather that you took from a dead turquoise deers body. you monster.", false, false, EquipmentType.NONE),
                new Item(179, "Blue deer leather", true, new Stats(), new Skills(), "Leather that you took from a dead blue deers body. you monster.", false, false, EquipmentType.NONE),
                new Item(180, "Purple deer leather", true, new Stats(), new Skills(), "Leather that you took from a dead purple deers body. you monster.", false, false, EquipmentType.NONE),
                new Item(181, "Red deer leather", true, new Stats(), new Skills(), "Leather that you took from a dead red deers body. you monster.", false, false, EquipmentType.NONE),
                new Item(182, "Black deer leather", true, new Stats(), new Skills(), "Leather that you took from a dead black deers body. you monster.", false, false, EquipmentType.NONE),
                new Item(183, "White deer leather", true, new Stats(), new Skills(), "Leather from a magnificent white deer. I hope you realize you might have killed the last of it's species.", false, false, EquipmentType.NONE),
                new Item(184, "Green deer meat", true, new Stats(), new Skills(), "Yuck, only poor folks eat green deer meat.", false, false, EquipmentType.NONE),
                new Item(185, "Turquoise deer meat", true, new Stats(), new Skills(), "The commoners favorite meat.", false, false, EquipmentType.NONE),
                new Item(186, "Blue deer meat", true, new Stats(), new Skills(), "Tastes the same as pig, and they've spent their lives rolling around in the mud.", false, false, EquipmentType.NONE),
                new Item(187, "Purple deer meat", true, new Stats(), new Skills(), "Deer meat with a wealthy taste.", false, true, EquipmentType.NONE),
                new Item(188, "Red deer meat", true, new Stats(), new Skills(), "Doctors say eating red meat is bad for you.. but it tastes good so who cares.", false, false, EquipmentType.NONE),
                new Item(189, "Black deer meat", true, new Stats(), new Skills(), "Finally some good fucking food.", false, false, EquipmentType.NONE),
                new Item(190, "White deer meat", true, new Stats(), new Skills(), "Now this is some real gourmet shit.", false, false, EquipmentType.NONE),
                new Item(191, "Raw green deer meat", true, new Stats(), new Skills(), "Yuck, only poor folks eat green deer meat.", false, false, EquipmentType.NONE),
                new Item(192, "Raw Turquoise deer meat", true, new Stats(), new Skills(), "The commoners favorite meat.", false, false, EquipmentType.NONE),
                new Item(193, "Raw blue deer meat", true, new Stats(), new Skills(), "Tastes the same as pig, and they've spent their lives rolling around in the mud.", false, false, EquipmentType.NONE),
                new Item(194, "Raw purple deer meat", true, new Stats(), new Skills(), "Deer meat with a wealthy taste.", false, false, EquipmentType.NONE),
                new Item(195, "Raw red deer meat", true, new Stats(), new Skills(), "Doctors say eating red meat is bad for you.. but it tastes good so who cares.", false, false, EquipmentType.NONE),
                new Item(196, "Raw black deer meat", true, new Stats(), new Skills(), "Finally some good fucking food.", false, false, EquipmentType.NONE),
                new Item(197, "Raw white deer meat", true, new Stats(), new Skills(), "Now this is some real gourmet shit.", false, false, EquipmentType.NONE),
                new Item(198, "Mallard duck breast", true, new Stats(), new Skills(), "No more quacking for this duck.", false, false, EquipmentType.NONE),
                new Item(199, "Tufted duck breast", true, new Stats(), new Skills(), "This duck waddled right into its own grave.", false, false, EquipmentType.NONE),
                new Item(200, "Raw mallard duck breast", true, new Stats(), new Skills(), "No more quacking for this duck.", false, false, EquipmentType.NONE),
                new Item(201, "Raw tufted duck breast", true, new Stats(), new Skills(), "This duck waddled right into its own grave.", false, false, EquipmentType.NONE),
                new Item(202, "Canada goose breast", true, new Stats(), new Skills(), "I'm glad the big pest is dead.", false, false, EquipmentType.NONE),
                new Item(203, "Greylag goose breast", true, new Stats(), new Skills(), "An average breast from an average goose.", false, false, EquipmentType.NONE),
                new Item(204, "Pinkfoot goose breast", true, new Stats(), new Skills(), "Not sure if this was a goose or a duck.", false, false, EquipmentType.NONE),
                new Item(205, "Raw canada goose breast", true, new Stats(), new Skills(), "I'm glad the big pest is dead.", false, false, EquipmentType.NONE),
                new Item(206, "Raw greylag goose breast", true, new Stats(), new Skills(), "An average breast from an average goose.", false, false, EquipmentType.NONE),
                new Item(207, "Raw pinkfoot goose breast", true, new Stats(), new Skills(), "Not sure if this was a goose or a duck.", false, false, EquipmentType.NONE),
                new Item(208, "Feathers", true, new Stats(), new Skills(), "Plucked from the dead body of some bird.", false, false, EquipmentType.NONE),
                new Item(209, "Rabbit", true, new Stats(), new Skills(), "Small, cute, and begging to be eaten.", false, false, EquipmentType.NONE),
                new Item(210, "Hare", true, new Stats(), new Skills(), "Big, fast, and very nutritious.", false, false, EquipmentType.NONE),
                new Item(211, "Raw rabbit", true, new Stats(), new Skills(), "Small, cute, and begging to be cooked.", false, false, EquipmentType.NONE),
                new Item(212, "Raw hare", true, new Stats(), new Skills(), "Big, fast, and soon to be very nutritious.", false, false, EquipmentType.NONE),
                new Item(213, "Lucky rabbit's foot", true, new Stats(), new Skills(), "The foot of a rabbit, it's said to bring luck when worn as an amulet.", false, false, EquipmentType.NONE),
                new Item(214, "Lucky rabbit's amulet", true, new Stats(), new Skills(), "An amulet with the foot of a rabbit. Don't let the animal protection see this.", false, true, EquipmentType.AMULET),
                new Item(215, "Pheasant breast", true, new Stats(), new Skills(), "It used to be a beatiful bird, and now it's a beatiful meal.", false, false, EquipmentType.NONE),
                new Item(216, "Woodpigeon breast", true, new Stats(), new Skills(), "The vermin of the sky, good riddance.", false, false, EquipmentType.NONE),
                new Item(217, "Corncrake breast", true, new Stats(), new Skills(), "A cute bird with a small brain.", false, false, EquipmentType.NONE),
                new Item(218, "Raw pheasant breast", true, new Stats(), new Skills(), "It used to be a beatiful bird, and now it's a beatiful corpse.", false, false, EquipmentType.NONE),
                new Item(219, "Raw woodpigeon breast", true, new Stats(), new Skills(), "The vermin of the sky, good riddance.", false, false, EquipmentType.NONE),
                new Item(220, "Raw corncrake breast", true, new Stats(), new Skills(), "A cute bird with a small brain.", false, false, EquipmentType.NONE),
                new Item(221, "Wood fishing rod", false, new Stats(), new Skills(), "A shabby wooden fishing rod.", false, false, EquipmentType.NONE),
                new Item(222, "Bronze fishing rod", false, new Stats(), new Skills(), "A bronze fishing rod, used for fishing.", false, false, EquipmentType.NONE),
                new Item(223, "Silver fishing rod", false, new Stats(), new Skills(), "A silver fishing rod, also used for fishing.", false, false, EquipmentType.NONE),
                new Item(224, "Gold fishing rod", false, new Stats(), new Skills(), "A gold fishing rod. mainly used for fishing.", false, false, EquipmentType.NONE),
                new Item(225, "Platinum fishing rod", false, new Stats(), new Skills(), "A platinum fishing rod. occasionally used for fishing.", false, false, EquipmentType.NONE),
                new Item(226, "Ruby fishing rod", false, new Stats(), new Skills(), "A platinum fishing rod decorated with a ruby.", false, true, EquipmentType.NONE),
                new Item(227, "Emerald fishing rod", false, new Stats(), new Skills(), "A platinum fishing rod decorated with an emerald.", false, false, EquipmentType.NONE),
                new Item(228, "Sapphire fishing rod", false, new Stats(), new Skills(), "A platinum fishing rod decorated with a sapphire.", false, false, EquipmentType.NONE),
                new Item(229, "Wood harpoon", false, new Stats(), new Skills(), "A shabby wooden harpoon.", false, false, EquipmentType.NONE),
                new Item(230, "Bronze harpoon", false, new Stats(), new Skills(), "A bronze harpoon.", false, false, EquipmentType.NONE),
                new Item(231, "Silver harpoon", false, new Stats(), new Skills(), "A silver harpoon. cool.", false, false, EquipmentType.NONE),
                new Item(232, "Gold harpoon", false, new Stats(), new Skills(), "A gold harpoon. epic.", false, false, EquipmentType.NONE),
                new Item(233, "Platinum harpoon", false, new Stats(), new Skills(), "A platinum harpoon. wicked.", false, false, EquipmentType.NONE),
                new Item(234, "Ruby harpoon", false, new Stats(), new Skills(), "A platinum harpoon decorated with a ruby.", false, false, EquipmentType.NONE),
                new Item(235, "Emerald harpoon", false, new Stats(), new Skills(), "A platinum harpoon decorated with an emerald.", false, false, EquipmentType.NONE),
                new Item(236, "Sapphire harpoon", false, new Stats(), new Skills(), "A platinum harpoon decorated with a sapphire.", false, false, EquipmentType.NONE),
                new Item(237, "Wood arrow on a rope", false, new Stats(), new Skills(), "A shabby wooden arrow on a rope.", false, false, EquipmentType.NONE),
                new Item(238, "Bronze arrow on a rope", false, new Stats(), new Skills(), "A bronze arrow on a rope.", false, false, EquipmentType.NONE),
                new Item(239, "Silver arrow on a rope", false, new Stats(), new Skills(), "A silver arrow on a rope. cool.", false, false, EquipmentType.NONE),
                new Item(240, "Gold arrow on a rope", false, new Stats(), new Skills(), "A gold arrow on a rope. epic.", false, false, EquipmentType.NONE),
                new Item(241, "Platinum arrow on a rope", false, new Stats(), new Skills(), "A platinum arrow on a rope. wicked.", false, false, EquipmentType.NONE),
                new Item(242, "Ruby arrow on a rope", false, new Stats(), new Skills(), "A platinum arrow on a rope decorated with a ruby.", false, false, EquipmentType.NONE),
                new Item(243, "Emerald arrow on a rope", false, new Stats(), new Skills(), "A platinum arrow on a rope decorated with an emerald.", false, false, EquipmentType.NONE),
                new Item(244, "Sapphire arrow on a rope", false, new Stats(), new Skills(), "A platinum arrow on a rope decorated with a sapphire.", false, false, EquipmentType.NONE),
                new Item(245, "Fishing bait", true, new Stats(), new Skills(), "Bait used for catching fish, when they are desperate enough to bite a hook.", false, false, EquipmentType.NONE),
                new Item(246, "Grubs", true, new Stats(), new Skills(), "Grubbies! saltwater fish love these.", false, false, EquipmentType.NONE),
                new Item(247, "Worms", true, new Stats(), new Skills(), "Yummy, delicous worms! freshwater fish love these.", false, false, EquipmentType.NONE),
                new Item(248, "Terrarium", true, new Stats(), new Skills(), "A little rectangular glass box used for breeding disgusting insects like grubs and worms.", false, false, EquipmentType.NONE),
                new Item(249, "Bass", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(250, "Esox", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(251, "Catfish", true, new Stats(), new Skills(), "Large freshwater fish, can also be found on the internet.", false, false, EquipmentType.NONE),
                new Item(252, "Walleye", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(253, "Muskellunge", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(254, "Tuna", true, new Stats(), new Skills(), "Large saltwater fish.", false, false, EquipmentType.NONE),
                new Item(255, "Tarpon", true, new Stats(), new Skills(), "Large saltwater fish.", false, false, EquipmentType.NONE),
                new Item(256, "Marlin", true, new Stats(), new Skills(), "Large saltwater fish with a massive nose.", false, false, EquipmentType.NONE),
                new Item(257, "Red drum", true, new Stats(), new Skills(), "Small saltwater fish.", false, false, EquipmentType.NONE),
                new Item(258, "Salmon", true, new Stats(), new Skills(), "Medium-sized saltwater fish.", false, false, EquipmentType.NONE),
                new Item(259, "Seed dibber", false, new Stats(), new Skills(), "A useful tool, commonly used to make holes with.", false, false, EquipmentType.NONE),
                new Item(260, "Spade", false, new Stats(), new Skills(), "A useful tool, commonly used to dig up plants or treasure!", false, false, EquipmentType.NONE),
                new Item(261, "Compost", true, new Stats(), new Skills(), "Literal cow shit, apparently it makes your plants grow faster.", false, false, EquipmentType.NONE),
                new Item(262, "Watering can", false, new Stats(), new Skills(), "A watering can is most commonly used for watering plants.", false, false, EquipmentType.NONE),
                new Item(263, "Tomato seed", true, new Stats(), new Skills(), "If you put this in the ground and water it every day, a tomato plant will grow!", false, false, EquipmentType.NONE),
                new Item(264, "Corn seed", true, new Stats(), new Skills(), "If you put this in the ground and water it every day, corn will grow!", false, false, EquipmentType.NONE),
                new Item(265, "Lettuce seed", true, new Stats(), new Skills(), "If you put this in the ground and water it every day, lettuce will grow!", false, false, EquipmentType.NONE),
                new Item(266, "Onion seed", true, new Stats(), new Skills(), "If you put this in the ground and water it every day, onions will grow!", false, false, EquipmentType.NONE),
                new Item(267, "Tomato", true, new Stats(), new Skills(), "Round, red and very juicy!", false, false, EquipmentType.NONE),
                new Item(268, "Corn", true, new Stats(), new Skills(), "Corn gang.", false, false, EquipmentType.NONE),
                new Item(269, "Lettuce", true, new Stats(), new Skills(), "Edible plants.", false, false, EquipmentType.NONE),
                new Item(270, "Onion", true, new Stats(), new Skills(), "You could technically eat these raw.", false, false, EquipmentType.NONE),
                new Item(271, "Berries", true, new Stats(), new Skills(), "Smash 'em together to make jam.", false, false, EquipmentType.NONE),
                new Item(272, "Hay", true, new Stats(), new Skills(), "Dried up grass, animals love this.", false, false, EquipmentType.NONE),
                new Item(273, "Animal medicine", true, new Stats(), new Skills(), "Only meant for animals, wesket!", false, false, EquipmentType.NONE),
                new Item(274, "Shears", false, new Stats(), new Skills(), "You can shear sheep with this.", false, false, EquipmentType.NONE),
                new Item(275, "Milk", true, new Stats(), new Skills(), "Came from a cows udders, think about that for a second.", false, false, EquipmentType.NONE),
                new Item(276, "Goat milk", true, new Stats(), new Skills(), "This milk was intended to feed baby goats with, but you took it.", false, false, EquipmentType.NONE),
                new Item(277, "Egg", true, new Stats(), new Skills(), "an egg.", false, false, EquipmentType.NONE),
                new Item(278, "Wool", true, new Stats(), new Skills(), "Very soft.", false, false, EquipmentType.NONE),
                new Item(279, "Cook's book", false, new Stats(), new Skills(), "It used to belong to the late town's cook, now it's yours.", false, false, EquipmentType.NONE),
                new Item(280, "Burnt deer meat", true, new Stats(), new Skills(), "This meat has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE),
                new Item(281, "Burnt fish", true, new Stats(), new Skills(), "This fish has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE),
                new Item(282, "Burnt duck", true, new Stats(), new Skills(), "This duck has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE),
                new Item(283, "Burnt goose", true, new Stats(), new Skills(), "This goose has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE),
                new Item(284, "Burnt rabbit", true, new Stats(), new Skills(), "This rabbit has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE),
                new Item(285, "Burnt bird", true, new Stats(), new Skills(), "This bird has lost it's taste and color, what a waste.", false, false, EquipmentType.NONE),
                new Item(286, "Over-fried egg", true, new Stats(), new Skills(), "Some would just call it burnt.", false, false, EquipmentType.NONE),
                new Item(287, "Deer with tomato", false, new Stats(), new Skills(), "The tomatoes look homegrown, it would be disrespectful not to eat them.", false, false, EquipmentType.NONE),
                new Item(288, "Deer with corn", false, new Stats(), new Skills(), "Seems like a solid meal.", false, false, EquipmentType.NONE),
                new Item(289, "Deer with lettuce", false, new Stats(), new Skills(), "Teasing the dead deer with his favorite grass.", false, false, EquipmentType.NONE),
                new Item(290, "Deer with onion", false, new Stats(), new Skills(), "Deer and onion.", false, false, EquipmentType.NONE),
                new Item(291, "Deer with cheese", false, new Stats(), new Skills(), "A lump of deer with some molten cheese on top.", false, false, EquipmentType.NONE),
                new Item(292, "Deer with milk", false, new Stats(), new Skills(), "The milk brings a creamy element to the meal.", false, false, EquipmentType.NONE),
                new Item(293, "Burnt deer with tomato", true, new Stats(), new Skills(), "The meal looks burnt, it would alright not to eat this.", false, false, EquipmentType.NONE),
                new Item(294, "Burnt deer with corn", true, new Stats(), new Skills(), "Seems like a burnt meal.", false, false, EquipmentType.NONE),
                new Item(295, "Burnt deer with lettuce", true, new Stats(), new Skills(), "Teasing the burnt dead deer with his favorite grass.", false, false, EquipmentType.NONE),
                new Item(296, "Burnt deer with onion", true, new Stats(), new Skills(), "Burnt deer and onion.", false, false, EquipmentType.NONE),
                new Item(297, "Burnt deer with cheese", true, new Stats(), new Skills(), "A burnt lump of deer with some molten cheese on top.", false, false, EquipmentType.NONE),
                new Item(298, "Burnt deer with milk", true, new Stats(), new Skills(), "The milk brings a creamy element to the meal. Unfortunately the meal needs more than that to be saved.", false, false, EquipmentType.NONE),
                new Item(299, "Duck with tomato", false, new Stats(), new Skills(), "Not a big meal, but it should do the job.", false, false, EquipmentType.NONE),
                new Item(300, "Duck with corn", false, new Stats(), new Skills(), "A lovely conbination.", false, false, EquipmentType.NONE),
                new Item(301, "Duck with lettuce", false, new Stats(), new Skills(), "The lettuce makes the duck feel at home one last time.", false, false, EquipmentType.NONE),
                new Item(302, "Duck with onion", false, new Stats(), new Skills(), "Duck and onion.", false, false, EquipmentType.NONE),
                new Item(303, "Duck with cheese", false, new Stats(), new Skills(), "You'd better tone down the mouth watering, the duck might swim away.", false, false, EquipmentType.NONE),
                new Item(304, "Duck with milk", false, new Stats(), new Skills(), "A daring combination.", false, false, EquipmentType.NONE),
                new Item(305, "Burnt duck with tomato", true, new Stats(), new Skills(), "I don't think this'll do the job.", false, false, EquipmentType.NONE),
                new Item(306, "Burnt duck with corn", true, new Stats(), new Skills(), "A true disappointment.", false, false, EquipmentType.NONE),
                new Item(307, "Burnt duck with lettuce", true, new Stats(), new Skills(), "Must have reminded it of the warm summer days.", false, false, EquipmentType.NONE),
                new Item(308, "Burnt duck with onion", true, new Stats(), new Skills(), "Burnt duck and onion.", false, false, EquipmentType.NONE),
                new Item(309, "Burnt duck with cheese", true, new Stats(), new Skills(), "You ruined it.", false, false, EquipmentType.NONE),
                new Item(310, "Burnt duck with milk", true, new Stats(), new Skills(), "I guess it didn't work out.", false, false, EquipmentType.NONE),
                new Item(311, "Goose with tomato", false, new Stats(), new Skills(), "HONK.", false, false, EquipmentType.NONE),
                new Item(312, "Goose with corn", false, new Stats(), new Skills(), "HONK HONK.", false, false, EquipmentType.NONE),
                new Item(313, "Goose with lettuce", false, new Stats(), new Skills(), "HONK HONK HONK.", false, false, EquipmentType.NONE),
                new Item(314, "Goose with onion", false, new Stats(), new Skills(), "Goose and onion.", false, false, EquipmentType.NONE),
                new Item(315, "Goose with cheese", false, new Stats(), new Skills(), "HONK HONK HONK HONK.", false, false, EquipmentType.NONE),
                new Item(316, "Goose with milk", false, new Stats(), new Skills(), "HONK x5.", false, false, EquipmentType.NONE),
                new Item(317, "Burnt goose with tomato", true, new Stats(), new Skills(), "sad honk.", false, false, EquipmentType.NONE),
                new Item(318, "Burnt goose with corn", true, new Stats(), new Skills(), "sad honk honk.", false, false, EquipmentType.NONE),
                new Item(319, "Burnt goose with lettuce", true, new Stats(), new Skills(), "sad honk honk honk.", false, false, EquipmentType.NONE),
                new Item(320, "Burnt goose with onion", true, new Stats(), new Skills(), "Burnt goose and onion.", false, false, EquipmentType.NONE),
                new Item(321, "Burnt goose with cheese", true, new Stats(), new Skills(), "sad honk honk honk honk.", false, false, EquipmentType.NONE),
                new Item(322, "Burnt goose with milk", true, new Stats(), new Skills(), "sad honk x5.", false, false, EquipmentType.NONE),
                new Item(323, "Rabbit with tomato", false, new Stats(), new Skills(), "Can't tell if it's a regular rabbit or a hare.. they're the same really.", false, false, EquipmentType.NONE),
                new Item(324, "Rabbit with corn", false, new Stats(), new Skills(), "Who thought this was a good idea?", false, false, EquipmentType.NONE),
                new Item(325, "Rabbit with lettuce", false, new Stats(), new Skills(), "Are you trying to feed a dead rabbit?", false, false, EquipmentType.NONE),
                new Item(326, "Rabbit with onion", false, new Stats(), new Skills(), "Rabbit and onion.", false, false, EquipmentType.NONE),
                new Item(327, "Rabbit with cheese", false, new Stats(), new Skills(), "This rabbit has a yellow blanket.", false, false, EquipmentType.NONE),
                new Item(328, "Rabbit with milk", false, new Stats(), new Skills(), "Looks like it drowned :(.", false, false, EquipmentType.NONE),
                new Item(329, "Burnt rabbit with tomato", true, new Stats(), new Skills(), "Burnt rabbit and hare still look the same.", false, false, EquipmentType.NONE),
                new Item(330, "Burnt rabbit with corn", true, new Stats(), new Skills(), "I told you it was a bad idea.", false, false, EquipmentType.NONE),
                new Item(331, "Burnt rabbit with lettuce", true, new Stats(), new Skills(), "Not surprised you burned that one.", false, false, EquipmentType.NONE),
                new Item(332, "Burnt rabbit with onion", true, new Stats(), new Skills(), "Burnt rabbit and onion.", false, false, EquipmentType.NONE),
                new Item(333, "Burnt rabbit with cheese", true, new Stats(), new Skills(), "No yellow blanket for this fella.", false, false, EquipmentType.NONE),
                new Item(334, "Burnt rabbit with milk", true, new Stats(), new Skills(), ":(", false, false, EquipmentType.NONE),
                new Item(335, "Fish with tomato", false, new Stats(), new Skills(), "Not very appealing.", false, false, EquipmentType.NONE),
                new Item(336, "Fish with corn", false, new Stats(), new Skills(), "As in 'A plate with fish and corn', not 'fishing with corn as bait'.", false, false, EquipmentType.NONE),
                new Item(337, "Fish with lettuce", false, new Stats(), new Skills(), "How creative.", false, false, EquipmentType.NONE),
                new Item(338, "Fish with onion", false, new Stats(), new Skills(), "Fish and onion.", false, false, EquipmentType.NONE),
                new Item(339, "Fish with cheese", false, new Stats(), new Skills(), "Not to be confused with fish and chips.", false, false, EquipmentType.NONE),
                new Item(340, "Fish with milk", false, new Stats(), new Skills(), "One last swim.", false, false, EquipmentType.NONE),
                new Item(341, "Burnt fish with tomato", true, new Stats(), new Skills(), "Even less appealing.", false, false, EquipmentType.NONE),
                new Item(342, "Burnt fish with corn", true, new Stats(), new Skills(), "Try paying more attention next time.", false, false, EquipmentType.NONE),
                new Item(343, "Burnt fish with lettuce", true, new Stats(), new Skills(), "Definitely original.", false, false, EquipmentType.NONE),
                new Item(344, "Burnt fish with onion", true, new Stats(), new Skills(), "Burnt fish and onion.", false, false, EquipmentType.NONE),
                new Item(345, "Burnt fish with cheese", true, new Stats(), new Skills(), "Atrocious.", false, false, EquipmentType.NONE),
                new Item(346, "Burnt fish with milk", true, new Stats(), new Skills(), "Read the name, what enlightenment did you expect to find here?.", false, false, EquipmentType.NONE),
                new Item(347, "Fried egg with tomato", false, new Stats(), new Skills(), "Great for breakfast.", false, false, EquipmentType.NONE),
                new Item(348, "Fried egg with corn", false, new Stats(), new Skills(), "Great for lunch.", false, false, EquipmentType.NONE),
                new Item(349, "Fried egg with lettuce", false, new Stats(), new Skills(), "Great for dinner.", false, false, EquipmentType.NONE),
                new Item(350, "Fried egg with onion", false, new Stats(), new Skills(), "Fried egg and onion", false, false, EquipmentType.NONE),
                new Item(351, "Fried egg with cheese", false, new Stats(), new Skills(), "Great as snack", false, false, EquipmentType.NONE),
                new Item(352, "Fried egg with milk", false, new Stats(), new Skills(), "Eat it whenever.", false, false, EquipmentType.NONE),
                new Item(353, "Burnt Fried egg with tomato", true, new Stats(), new Skills(), "Not so great for breakfast.", false, false, EquipmentType.NONE),
                new Item(354, "Burnt Fried egg with corn", true, new Stats(), new Skills(), "Not so great for lunch.", false, false, EquipmentType.NONE),
                new Item(355, "Burnt Fried egg with lettuce", true, new Stats(), new Skills(), "Not so great for dinner", false, false, EquipmentType.NONE),
                new Item(356, "Burnt Fried egg with onion", true, new Stats(), new Skills(), "Burnt egg and onion", false, false, EquipmentType.NONE),
                new Item(357, "Burnt Fried egg with cheese", true, new Stats(), new Skills(), "Not so great as snack.", false, false, EquipmentType.NONE),
                new Item(358, "Burnt Fried egg with milk", true, new Stats(), new Skills(), "Don't eat it.", false, false, EquipmentType.NONE),
                new Item(359, "Egg salad", false, new Stats(), new Skills(), "An egg with some weeds or something.", false, false, EquipmentType.NONE),
                new Item(360, "Cheese salad", false, new Stats(), new Skills(), "Healthy salad.", false, false, EquipmentType.NONE),
                new Item(361, "Cheese", true, new Stats(), new Skills(), "This also came from a cow's udders indirectly.", false, false, EquipmentType.NONE),
                new Item(362, "Goat cheese", true, new Stats(), new Skills(), "Significantly different from a cow's cheese.", false, false, EquipmentType.NONE),
                new Item(363, "Jam", true, new Stats(), new Skills(), "A bunch of berries mashed together.", false, false, EquipmentType.NONE),
                new Item(364, "Wool carpet", true, new Stats(), new Skills(), "A very soft carpet.", false, false, EquipmentType.NONE),
                new Item(365, "Wool blanket", true, new Stats(), new Skills(), "A very soft blanket.", false, false, EquipmentType.NONE),
                new Item(366, "Bronze dagger", false, new Stats(), new Skills(), "a regular dagger made out of bronze.", false, true, EquipmentType.OFFHAND),
                new Item(367, "Silver dagger", false, new Stats(), new Skills(), "a regular dagger made out of silver.", false, true, EquipmentType.OFFHAND),
                new Item(368, "Gold dagger", false, new Stats(), new Skills(), "a regular dagger made out of gold.", false, true, EquipmentType.OFFHAND),
                new Item(369, "Platinum dagger", false, new Stats(), new Skills(), "a regular dagger made out of platinum.", false, true, EquipmentType.OFFHAND),
                new Item(370, "Ruby dagger", false, new Stats(), new Skills(), "a dagger made out of platinum. There's a ruby in the rain-guard.", false, true, EquipmentType.OFFHAND),
                new Item(371, "Emerald dagger", false, new Stats(), new Skills(), "a dagger made out of platinum. There's an emerald in the rain-guard.", false, true, EquipmentType.OFFHAND),
                new Item(372, "Sapphire dagger", false, new Stats(), new Skills(), "a dagger made out of platinum. There's a sapphire in the rain-guard.", false, true, EquipmentType.OFFHAND),
                new Item(373, "Raw bass", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(374, "Raw esox", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(375, "Raw catfish", true, new Stats(), new Skills(), "Large freshwater fish, can also be found on the internet.", false, false, EquipmentType.NONE),
                new Item(376, "Raw walleye", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(377, "Raw muskellunge", true, new Stats(), new Skills(), "Medium-sized freshwater fish.", false, false, EquipmentType.NONE),
                new Item(378, "Raw tuna", true, new Stats(), new Skills(), "Large saltwater fish.", false, false, EquipmentType.NONE),
                new Item(379, "Raw tarpon", true, new Stats(), new Skills(), "Large saltwater fish.", false, false, EquipmentType.NONE),
                new Item(380, "Raw marlin", true, new Stats(), new Skills(), "Large saltwater fish with a massive nose.", false, false, EquipmentType.NONE),
                new Item(381, "Raw red drum", true, new Stats(), new Skills(), "Small saltwater fish.", false, false, EquipmentType.NONE),
                new Item(382, "Raw salmon", true, new Stats(), new Skills(), "Medium-sized saltwater fish.", false, false, EquipmentType.NONE),
                new Item(383, "Rope", true, new Stats(), new Skills(), "A length of rope made out of hair, yuck.", false, false, EquipmentType.NONE),
            };

            EquipmentArray = new EquipmentItemMultiArray[items.Count];
            InventoryIcon = new Sprite[items.Count];
            for (int i = 0; i < items.Count; i++)
            {
                EquipmentArray[i] = new EquipmentItemMultiArray();
                EquipmentArray[i].EquipSprites = new Sprite[4];
                for (int j = 0; j < EquipmentArray[i].EquipSprites.Length; j++)
                {
                    InventoryIcon[i] = Resources.Load<Sprite>($"Item/{i}/item_{i}");
                    EquipmentArray[i].EquipSprites[j] = Resources.Load<Sprite>($"Item/{i}/item_{i}_{j}");
                    ((Item)items[i]).SetSprites(InventoryIcon[i], EquipmentArray[i]);
                }
            }

            //for(int i = 0; i < InventoryIcon.Length; i++)
            //    ((Item)items[i]).SetSprites(InventoryIcon[i], EquipmentArray[i]);



            CrLogger.Log(this, "The item database was built succesfully");
        }

        public Item GetItem(int id)
        {
            Item it;
            it = items.Where(i => i.Id == id).FirstOrDefault() as Item;
            return it;
        }
    }
}
